<script>
      var currency = {};
      currency.symbol = '<?php echo $this->currency["symbol"]; ?>';
      currency.decimalssep = "<?php echo $this->currency['decimalsSep']; ?>";
      currency.thousandssep = "<?php echo $this->currency['thousandsSep']; ?>";
      currency.alignment = "<?php echo $this->currency['alignment']; ?>";
      currency.precision = "<?php echo $this->currency['precision']; ?>";
      currency.abrv = "<?php echo $this->currency['abrv']; ?>";
      currency.showabrv = "<?php echo $this->currency['showabrv']; ?>";
</script>