<div class="datatable-page">
    <div class="container">
        <div class="cm-holder">
            <div class="data-table-wrapper">
                <?php echo $this->unescape($this->top_snapin_html); ?>
                <?php if (!$this->hasPermission && !$this->loggedin) { ?>
                    <div class="alert alert-danger ce-alert ce-alert-error">
                        <?php echo $this->user->lang('Guest ticket access is disabled, please '); ?>
                        <a href='index.php?fuse=home&view=login'>
                            <?php echo $this->user->lang('login'); ?>
                        </a>
                    </div>
                <?php } else if ($this->user->isAdmin()) { ?>
                    <div class="alert alert-danger ce-alert ce-alert-error">
                        <?php echo $this->user->lang('You are currently logged in as an administrator.  Please log out of the administration panel before attempting to submit a support ticket.'); ?>
                    </div>
                <?php } else { ?>

                <div class="head">
                    <h1>
                        <?php echo $this->user->lang('Submit Ticket'); ?>
                    </h1>
                </div>
                <div class="cs-padding">
                    <form method="post" enctype="multipart/form-data" action="index.php?fuse=support&controller=ticket&action=saveticket" id="support-ticket-form">
                        <input type="hidden" name="userid" value="<?php echo $this->user->getId(); ?>">
                        <?php if (isset($this->clientid)) { ?>
                            <input type="hidden" name="clientid" value="<?php echo $this->clientid; ?>">
                        <?php } ?>
                        <div class="row">
                            <div class="file-ticket-desc col-12">
                                <?php
                                    echo $this->user->lang(
                                    'If you can not find a solution to your issue in our %sknowledgebase%s, please submit your question below.',
                                    '<a href="index.php?fuse=knowledgebase&controller=articles&view=main">',
                                    '</a>'
                                ); ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-12 col-md-6">
                                <label for="ticket-type" class="col-form-label">
                                    <?php echo $this->user->lang("What can we assist you with?");?>
                                </label>
                                <select data-parsley-pattern='^[1-9]\d*$' name="ticket-type" class="drop-ticket-type form-control searchSelect2">
                                    <?php foreach ($this->tickettypes as $ticketType) { ?>
                                    <option value="<?php echo $ticketType['value']; ?>" <?php echo $ticketType['selected']; ?>>
                                        <?php echo $ticketType['name'];?>
                                    </option>
                                <?php } ?>
                                </select>
                                <div class="top-questions-block d-none">
                                    <h4 class="review-questions-header pt-2">
                                        <?php echo $this->user->lang("Review top questions for");?>
                                        <span class="review-questions-fortype"></span>
                                    </h4>
                                    <div class='review-questions-desc'>
                                    </div>
                                </div>
                            </div>
                            <?php if (isset($this->domainDropDown)) { ?>
                            <div class="form-group col-12 col-md-6">
                                <label class="col-form-label block-label">
                                    <?php echo $this->user->lang("What package is this in reference to?"); ?>
                                </label>
                                <?php echo $this->unescape($this->domainDropDown); ?>
                            </div>
                        <?php } ?>

                        </div>

                    <?php if ($this->user->getId() == 0) { ?>
                    <div class="row">
                        <div class="form-group col-12 col-md-6">
                            <label for="guestName"><?php echo $this->user->lang('Full Name'); ?></label>
                            <input class="form-control" data-parsley-required type="text" id="guestName" name="guestName" placeholder="<?php echo $this->user->lang('First and Last Name'); ?>" value="">
                        </div>
                        <div class="form-group col-12 col-md-6">
                            <label for="guestEmail"><?php echo $this->user->lang('Email'); ?></label>
                            <input class="form-control" data-parsley-required data-type="email" type="email" id="guestEmail" name="guestEmail" placeholder="<?php echo $this->user->lang('Your Email'); ?>"
                            value="">
                        </div>
                    </div>
                    <?php } ?>
                    <div class="row">
                        <div class="form-group col-12 col-md-6">
                            <label for="subject" class="col-form-label">
                                <?php echo $this->user->lang('Subject');?>
                            </label>
                            <input type="text" dir="auto" onkeyup="loadKBArticles(event);" name="subject" class="ticket-subject form-control" data-parsley-required value="" >
                            <div class="subject-article-matches"></div>
                        </div>
                    </div>


                        <div class="row">
                            <div class="form-group col-12">
                                <label for="message" class="col-form-label">
                                    <?php echo $this->user->lang('Question'); ?>
                                </label>
                                <textarea rows="10" dir="auto" class="support-ticket-message ticket-align form-control" name="message" data-parsley-required></textarea>
                            </div>
                        </div>
                        <?php if ($this->maxfilesize > 0 && $this->extns) { ?>
                        <div class="row">
                            <div class="form-group col-12">
                                <div class="share-upload-desc">
                                <?php echo $this->user->lang("Sharing a picture will help us understand your question even more");?>
                                <?php echo $this->user->lang("Max file size: %s", $this->maxfilesize);?>
                                    <?php if ($this->extns != '*') { ?>
                                        - <span data-html="true" data-toggle="tooltip" data-placement="top" title="<?php echo $this->user->lang("Allowed file extensions: %s", $this->extnsmessage);?>"><?php echo $this->user->lang('See Allowed Extensions') ?></span>
                                    <?php } ?>
                                    </div>
                                   <div id="fileFieldsContainer" class="form-actions">
                                        <div id="fileFields_" class="d-none file-upload ">
                                            <label class="btn-file">
                                                <input class="file_upload_input" type="file">
                                            </label>
                                            <a class="d-none col-6 col-lg-3 deleteButton">
                                                <?php echo $this->user->lang('Delete'); ?>
                                            </a>
                                        </div>
                                    </div>
                                    <a id="new-file-button" class="" href="#">
                                        <?php echo $this->user->lang('Add a New File'); ?>
                                    </a>
                                    <input type="hidden" name="validExtns" value="<?php echo $this->extns; ?>" />
                                </div>
                            </div>
                        <?php } ?>

                    <div class="row fieldset-customfields d-none">
                        <div class="form-group col-12 d-one">
                            <h1 class="customfields-header">
                                <?php
                                echo $this->user->lang("Additional information that may assist us");
                                ?>
                            </h1>
                            <div class="customfields customfields-wrapper"></div>
                        </div>
                    </div>

                <?php if ($this->showCaptcha) { ?>
                    <div class="row">
                        <div class="form-group col-12">
                            <?php echo $this->unescape($this->captchaHtml); ?>
                        </div>
                    </div>
                <?php } ?>
                    <div class="row">
                       <div class="col-md-5 col-12 form-group">
                            <input type="submit" class="app-btns primary" value="<?php echo $this->user->lang('Submit Ticket'); ?>">
                        </div>
                    </div>
                    </form>
                </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>

<script type="text/html" id="articles">
    <table class='table table-striped table-hover'>
        <tbody>
            {{#articles}}
                <tr>
                    <td>{{#categoryname}}<a target="_blank" href="index.php?fuse=knowledgebase&controller=articles&view=main&categoryId={{categoryid}}"><span class="label label-important">{{categoryname}}</span></a>&nbsp&nbsp{{/categoryname}}<a target="_blank" href='index.php?fuse=knowledgebase&view=article&controller=articles&articleId={{id}}'>{{title}}</a>
                    </td>
                </tr>
            {{/articles}}
        </tbody>
    </table>
</script>

<script>
    $('#support-ticket-form').parsley();

    $('.drop-ticket-type').on('change',function(){
        $('.review-questions-fortype').html('');
        var self = this;
        $('.top-questions-block table').remove();
        $('.loading-ticket-type').removeClass('d-none');
        //gets any top questions we might have
        $.get('index.php?fuse=support&controller=ticket&action=toparticles&typeid='+$(this).val(),function(xhr){
            var html = "";
            if (xhr.articles.length > 0) {
                var template = $('#articles').html();
                html = Mustache.render(template, xhr);
                $('.top-questions-block .review-questions-desc').after(html);
                $('.top-questions-block').removeClass('d-none');
                $('.loading-ticket-type').addClass('d-none');
                $('.review-questions-fortype').append(' '+$('.drop-ticket-type option:selected').text());
            } else {
                $('.top-questions-block').addClass('d-none');
                $('.loading-ticket-type').addClass('d-none');
            }
        })
        loadCustomFields($(this).val());
    });

    //if coming back to page and already have something selected
    //let's pull the popular articles
    if ($('.drop-ticket-type').val() > 0 ) {
        $('.drop-ticket-type').trigger('click');
    }

    //if we go back and we have content in subject let's call the query
    if ($.trim($('.ticket-subject').val()) != "") {
        $('.ticket-subject').keyup();
    }

    if ($('#new-file-button').length) {
        // $('input[type=file]').bootstrapFileInput();
        $('input[type=file]').change(support.selectedFile);

        $('#new-file-button').on('click',function(e){
            e.preventDefault();
            support.cloneAttchInput();
        });

        support.cloneAttchInput();
    }

    function loadCustomFields(ticketType)
    {
        $('.fieldset-customfields').addClass('d-none');
        $('.fieldset-customfields .customfields').empty();

        $.get('index.php?fuse=support&controller=ticket&view=customfieldsfortype', {
            ticketType: ticketType
        }, function(data) {

            if (data != '') {
                $('.customfields-wrapper').html(data);
                $('.fieldset-customfields').removeClass('d-none');

            } else {
                $('.fieldset-customfields').addClass('d-none');
            }
        });
    }

    function loadKBArticles(e, path) {
        if (!path) path = "";

        if (e.which == 13) {
          window.clearTimeout(clientexec.timer_typing);
          e.preventDefault();
        } else {
          window.clearTimeout(clientexec.timer_typing);
          clientexec.timer_typing = window.setTimeout( function() {
              var str = $.trim($('.ticket-subject').val());
              if(str == "") {
                    $('.subject-article-matches').html('').addClass('d-none');
                    window.clearTimeout(clientexec.timer_typing);
                    return;
              }
              $.get(path + 'index.php?fuse=knowledgebase&action=livearticlesearch',{subject:str, path:path, limit: 5},function(data){
                if (data.articles.length == 0) {
                    html = "";
                    $('.subject-article-matches').addClass('d-none');
                    return;
                } else if (data.articles.length == 1) {
                    html = clientexec.lang("There is 1 article that might answer your question.");
                } else {
                    html = clientexec.lang("There are % articles that might answer your question.", data.articles.length);
                }

                var template = document.getElementById('articles').innerHTML;
                html = "<div class='subject-article-desc'>"+html+"</div>" + Mustache.render(template, data);
                $('.subject-article-matches').html(html).fadeIn();
              });
          }, 800 );

        }
    }
</script>
