<h1><?php echo $this->user->lang('Email History'); ?></h1>

<div class="form-group col-xs-12">
    <div class="table-responsive">
        <table id="emails-grid" class="table table-striped">
            <thead>
                <tr>
                    <th></th>
                    <th><?php echo $this->user->lang('Subject'); ?></th>
                    <th><?php echo $this->user->lang('Date Sent'); ?></th>
                    <th><?php echo $this->user->lang('From'); ?></th>
                </tr>
            </thead>
        </table>
    </div>
</div>