<?php if (count($this->snapins) > 0) {
    //let's get snapin menus
    $pluginmenu = array(
        'tools' => '',
        'products' => '',
        'billing' => '',
        'support' => '',
        'profile' => '',
    );
    foreach ($this->snapins as $snapin) {
        if (!isset($snapin->mapping['topmenu'])) {
            $snapin->mapping['topmenu'] = array();
        }
        foreach ($snapin->mapping['topmenu'] as $hash_key => $map) {
            if ($map['type'] != "public") {
                continue;
            }
            $li = '<li><a href="index.php?fuse=admin&view=snapin&controller=snapins&plugin=' . $snapin->getInternalName() . '&h=' . urlencode(base64_encode("topmenu:" . $hash_key)) . '">' . $map['title'] . '</a></li>';
            switch ($map['loc']) {
                case "tools":
                    $pluginmenu['tools'] .= $li;
                    break;
                case "support":
                    $pluginmenu['support'] .= $li;
                    break;
                case "products":
                    $pluginmenu['products'] .= $li;
                    break;
                case "billing":
                    $pluginmenu['billing'] .= $li;
                    break;
                case "profile":
                    $pluginmenu['profile'] .= $li;
                    break;
            }
        }
    }
} ?>
<nav class="navbar ce-topnavbar <?php echo ($this->overallstyle == 'dark')? 'navbar-inverse' : 'navbar-default';?>">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
       <div class="navbar-collapse collapse" id="menu">
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <a href="index.php">
                        <?php echo $this->user->lang("Home");?>
                    </a>
                </li>
            <?php if ($this->loggedin) { ?>
                <li>
                    <a href="index.php?fuse=home&view=dashboard">
                        <?php echo $this->user->lang("Dashboard");?>
                    </a>
                </li>
            <?php } ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <?php echo $this->user->lang("Packages");?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="order.php">
                                <?php echo $this->user->lang("Order new services");?>
                            </a>
                        </li>
            <?php if ($this->loggedin || $pluginmenu['products'] != '') { ?>
                <?php if ($this->loggedin) { ?>
                        <li>
                            <a href="index.php?fuse=clients&controller=products&view=products">
                                <?php echo $this->user->lang("Package list");?>
                            </a>
                        </li>
                    <?php } ?>
                    <?php if ($pluginmenu['products'] != '') { ?>
                        <?php echo $pluginmenu['products']; ?>
                    <?php } ?>
                <?php } ?>
                    </ul>
                </li>
            <?php if ($this->loggedin || $pluginmenu['billing'] != '') { ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <?php echo $this->user->lang("Billing");?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                    <?php if ($this->loggedin) { ?>
                        <li>
                            <a href="index.php?fuse=billing&controller=invoice&view=allinvoices&filter=open">
                                <?php echo $this->user->lang("My invoices");?>
                            </a>
                        </li>
                        <li>
                            <a href="index.php?fuse=clients&controller=userprofile&view=paymentmethod">
                                <?php echo $this->user->lang("Edit Payment Method");?>
                            </a>
                        </li>
                    <?php } ?>
                    <?php if ($pluginmenu['billing'] != '') { ?>
                        <?php echo $pluginmenu['billing']; ?>
                    <?php } ?>
                    </ul>
                </li>
            <?php } ?>
            <?php if ($this->user->hasPermission('support_view') || $this->user->hasPermission('knowledgebase_view') || $this->user->hasPermission('support_submit_ticket') || $pluginmenu['support'] != '') { ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <?php echo $this->user->lang("Support");?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                    <?php if ($this->user->hasPermission('support_view')) { ?>
                        <li>
                            <a href="index.php?fuse=support&controller=ticket&view=alltickets&filter=all">
                                <?php echo $this->user->lang("My tickets");?>
                            </a>
                        </li>
                    <?php } ?>
                    <?php if ($this->user->hasPermission('knowledgebase_view')) { ?>
                        <li>
                            <a href="index.php?fuse=knowledgebase&controller=articles&view=main">
                                <?php echo $this->user->lang("Search knowledge base");?>
                            </a>
                        </li>
                    <?php } ?>
                    <?php if ($this->user->hasPermission('support_submit_ticket')) { ?>
                        <li>
                            <a href='index.php?fuse=support&controller=ticket&view=submitticket'>
                                <?php echo $this->user->lang("Submit a request"); ?>
                            </a>
                        </li>
                    <?php } ?>
                    <?php if ($pluginmenu['support'] != '') { ?>
                        <?php echo $pluginmenu['support']; ?>
                    <?php } ?>
                    </ul>
                </li>
            <?php } ?>
            <?php if ($pluginmenu['tools'] != '') { ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <?php echo $this->user->lang("Plugins");?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <?php echo $pluginmenu['tools']; ?>
                    </ul>
                </li>
            <?php } ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <?php if ($this->loggedin) { ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <?php echo $this->user->lang("Welcome %s %s.", $this->escape($this->user->getFirstName()), substr($this->escape($this->user->getLastName()), 0, 1)); ?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                    <?php if ($this->user->hasPermission('clients_edit_customers')) { ?>
                        <li>
                            <a href="index.php?fuse=clients&controller=userprofile&view=editprofile">
                                <?php echo $this->user->lang("Edit Profile");?>
                            </a>
                        </li>
                    <?php } ?>
                        <li>
                            <a href="index.php?fuse=clients&controller=userprofile&view=editpassword">
                                <?php echo $this->user->lang("Change Password");?>
                            </a>
                        </li>
                        <li>
                            <a href="index.php?fuse=clients&controller=userprofile&view=altemails">
                                <?php echo $this->user->lang("Alternate Accounts");?>
                            </a>
                        </li>
                        <li>
                            <a href="index.php?fuse=clients&controller=userprofile&view=notes">
                                <?php echo $this->user->lang("Account Notes");?>
                            </a>
                        </li>
                    <?php if ($this->user->hasPermission('clients_view_emails')) { ?>
                        <li>
                            <a href="index.php?fuse=clients&controller=index&view=emailhistory">
                                <?php echo $this->user->lang("Email History");?>
                            </a>
                        </li>
                    <?php } ?>
                    <?php if ($pluginmenu['profile'] != '') { ?>
                        <?php echo $pluginmenu['profile']; ?>
                    <?php } ?>
                        <li class="li-link-signoff">
                            <a href="index.php?fuse=admin&action=Logout" class="link-signoff">
                                <?php echo $this->user->lang("Logoff");?>
                            </a>
                        </li>
                    </ul>
                </li>
            <?php } elseif ($this->user->isAdmin()) { ?>
                <li>
                    <a href="<?php echo CE_Lib::getSoftwareURL() . NE_CONTROLLER_ADMIN_DIR; ?>/index.php">
                        <span class="link-admin-loggedin label label-important">
                            &nbsp;&nbsp;<?php echo $this->user->lang("You are currently logged in as admin");?>&nbsp;&nbsp;
                        </span>
                    </a>
                </li>
            <?php } else { ?>
                <?php if ($pluginmenu['profile'] != '') { ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <?php echo $this->user->lang("Welcome");?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="index.php?fuse=home&view=login" class="link-signoff">
                                <?php echo $this->user->lang("Login"); ?>
                            </a>
                        </li>
                        <?php echo $pluginmenu['profile']; ?>
                    </ul>
                </li>
                <?php } else { ?>
                <li>
                    <a href="index.php?fuse=home&view=login" class="link-signoff">
                        <?php echo $this->user->lang("Login"); ?>
                    </a>
                </li>
                <?php } ?>
            <?php } ?>
            </ul>
            <?php if (count($this->langauges) > 1) { ?>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <?php echo $this->user->lang("Language");?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                    <?php foreach ($this->langauges as $lang) { ?>
                        <li>
                            <a href="#" class="language-selector" data-language="<?php echo $lang; ?>">
                                <?php echo ucwords($lang); ?>
                            </a>
                        </li>
                    <?php } ?>
                    </ul>
                </li>
            </ul>
            <?php } ?>
        </div>
    </div>
</nav>