<?php
// get saved color or if not present grab the selected template options
// template_color is only available if color was passed via url
$stylecolor =  ($this->template_color != "") ? $this->template_color : $this->templateOptions['Theme Color']['value'];
$stylecolor = str_replace(" ", "_", strtolower($stylecolor));
if ($stylecolor == '') {
    $stylecolor = 'blue';
}

// let's not pass background
// if we are not using style
if (!$this->gHideStyle) {
    $this->publichelper();
    $stylebody = "";
} else {
    $stylebody = "background-color: rgba(0, 0, 0, 0);";
}

// get saved style or if not present grab the selected template options
// template_color is only available if color was passed via url
$overallstyle =  ($this->template_style != "") ? $this->template_style : $this->templateOptions['Theme Style']['value'];
$overallstyle = strtolower($overallstyle);
if ($overallstyle == '') {
    $overallstyle = 'light';
}

if ($this->pageTitle == "") {
    $original_title = "Untitled (".$this->gFuse."/".$this->gView.") - ".$this->gCompanyName;
} else {
    $original_title = ucfirst($this->pageTitle)." - ".$this->gCompanyName;
}

if (count($this->gErrorMessages) > 0) {
    $strErrorMessage = "";
    foreach ($this->gErrorMessages as $message) {
        if ($strErrorMessage != '') {
            $strErrorMessage .= '<br>';
        }
        $strErrorMessage .= $message;
    }
}

if (count($this->gMessages) > 0) {
    $strSuccessMessage = "";
    foreach ($this->gMessages as $message) {
        if ($strSuccessMessage != '') {
            $strSuccessMessage .= '<br>';
        }
        $strSuccessMessage .= $message;
    }
}

if (count($this->gSuccessMessages)>0) {
    $strSuccessMessage = "";
    foreach ($this->gSuccessMessages as $message) {
        if ($strSuccessMessage != '') {
            $strSuccessMessage .= '<br>';
        }
        $strSuccessMessage .= $message;
    }
}

?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php if ($this->seoDesc !='') {?>
        <meta name="description" content="<?php echo $this->seoDesc; ?>" />
        <?php } ?>
        <?php if ($this->seoKeywords !='') {?>
        <meta name="keywords" content="<?php echo $this->seoKeywords; ?>" />
        <?php } ?>
        <title><?php echo $original_title; ?></title>
        <link rel="Shortcut Icon" href="favicon.ico" />
        <link href='//fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>
        <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
        <link href='//fonts.googleapis.com/css?family=Quattrocento+Sans:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <?php if ($this->useCDN === true) { ?>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
        <?php } else { ?>
        <link rel="stylesheet" href="templates/default/css/bootstrap.min.css">
        <?php } ?>
    <?php if (!$this->gHideStyle) { ?>
        <link type="text/css" rel="stylesheet" href="library/utilities/min/index.php?g=publiccss<?php echo $this->debugMinifier? '&amp;debug=true' : '';?>&ver=<?php echo $this->gInstalledVersion;?>" />
        <link href="<?php echo $this->templateCSS['style']; ?>?ver=<?php echo $this->gInstalledVersion; ?>" rel="stylesheet" />
        <link href="<?php echo $this->templateCSS['color-schemes']; ?>?ver=<?php echo $this->gInstalledVersion; ?>" rel="stylesheet" />
        <link href="<?php echo $this->templateCSS['bootstrap-overrides']; ?>?ver=<?php echo $this->gInstalledVersion; ?>" rel="stylesheet" />
    <?php } ?>
    <?php if ($this->gCSSFiles != '') { ?>
        <link rel="stylesheet" type="text/css" href="library/utilities/min/index.php?f=<?php echo $this->gCSSFiles;?><?php echo $this->debugMinifier? '&amp;debug=true' : '';?>&ver=<?php echo $this->gInstalledVersion;?>" />
    <?php } ?>
    <!--[if lt IE 9]>
        <script data-cfasync="false" src="javascript/html5_shiv.js"></script>
    <![endif]-->
        <?php if ($this->useCDN === true) { ?>
        <script data-cfasync="false" src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
        <?php } else { ?>
        <script data-cfasync="false" src="templates/default/js/jquery-1.12.4.min.js"></script>
        <?php } ?>
    <?php if (!$this->gHideStyle) { ?>
        <?php echo $this->unescape($this->headHTML);?>
    <?php } ?>
    </head>

    <body style="<?php echo $stylebody;?>" class="ce-bgcolor-<?php echo $stylecolor;?> ce-overall-<?php echo $overallstyle;?>">

    <?php if ($this->gHideStyle) { ?>
        <?php echo $this->layout()->CONTENT; ?>
    <?php } else { ?>
        <?php echo $this->unescape($this->bodyHTML); ?>
        <div id="msg-div" class="msg-div-wrapper hidden">
            <div id="msg-div-inner" class="msg-div-inner"></div>
        </div>
        <div class="page-header-top">
            <div class="container <?php echo ($this->loggedIn)?"loggedin":'';?>">
                <h1 class="client-portal-name">
                <?php if ($this->logoURL) : ?>
                    <img class="public-logo img-responsive" src="<?php echo $this->logoURL ?>" />
                <?php else : ?>
                    <?php echo $this->user->lang("Client portal");?>
                <?php endif ?>
                </h1>
            </div>
        </div>

        <div class="container ce-container<?php echo ($this->loggedIn)?' loggedin':''; ?>">
            <?php echo $this->partial('views/layoutpartials/topmenu.phtml', array(
                'snapins' => $this->snapins,
                'user' => $this->user,
                'gView' => $this->gView,
                'loggedin' => $this->loggedIn,
                'overallstyle' => $overallstyle,
                'has_invoices' => $this->gHasInvoices,
                'templateOptions' => $this->templateOptions,
                'langauges' => CE_Lib::getEnabledLanguages()
            )); ?>
            <div class="col-xs-12 ce-main <?php echo ($this->in_cart)?'cart':'notcart'; ?>">
                <div class="col-xs-12 inner ce-main-inner">
                    <?php echo $this->unescape($this->tplBreadCrumb); ?>
                <?php if (count($this->gErrorMessages) > 0) { ?>
                    <div class="alert ce-alert alert-danger alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <?php echo $strErrorMessage; ?>
                    </div>
                <?php } ?>
                <?php if (count($this->gMessages) > 0) { ?>
                    <div class="alert ce-alert alert-warning alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <?php echo $strSuccessMessage; ?>
                    </div>
                <?php } ?>
                <?php if (count($this->gSuccessMessages)>0) { ?>
                    <div class="alert ce-alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <?php echo $strSuccessMessage; ?>
                    </div>
                <?php }?>
                    <?php echo $this->layout()->CONTENT; ?>
                </div>
            </div>

        <?php if (!CE_Lib::hasAttribute("nobranding")) { ?>
            <div class="poweredby col-xs-12">
                <span><?php echo $this->user->lang("Powered by");?></span>
                <a href="http://www.clientexec.com?source=poweredby" target="_new">
                    <img class="brand-logo img-responsive" src="templates/default/img/logo_text.png">
                </a>
            </div>
        <?php } ?>
        </div>
    <?php } ?>

        <script data-cfasync="false" type="text/javascript">
            var clientexec = {};
            clientexec.template = {};
            clientexec.dateFormat = "<?php echo $this->gDateFormat;?>";
            clientexec.template.themecolor = "ce-bgcolor-<?php echo $stylecolor; ?>";
            clientexec.isAdmin = <?php echo ($this->gIsAdmin) ? "true": "false";?>;
            clientexec.sessionHash = "<?php echo $this->gHash; ?>";
            clientexec.relativePath = "<?php echo $this->gRelativePath; ?>";
            clientexec.fuse = "<?php echo $this->gFuse; ?>";
            clientexec.view = "<?php echo $this->gView; ?>";
            clientexec.original_title = "<?php echo $original_title;?>";
            clientexec.log_usage = <?php echo $this->log_usage;?>;
            clientexec.captcha = <?php echo $this->captcha? 'true' : 'false' ?>;
        <?php if ($this->loggedIn) { ?>
            clientexec.customerId = "<?php echo $this->gCustomerId;?>";
            clientexec.customerFirstName = "<?php echo $this->gUserFirstName; ?>";
            clientexec.customerFullName = "<?php echo $this->escape($this->user->getFullName()); ?>";
            clientexec.customerEmail = "<?php echo $this->escape($this->user->getEmail()) ?>";
        <?php } else { ?>
            clientexec.customerId = 0;
            clientexec.customerEmail = '';
        <?php } ?>
        </script>

    <?php if (!$this->gHideStyle) { ?>
        <?php if ($this->useCDN === true) { ?>
        <script data-cfasync="false" src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
        <?php } else { ?>
            <script data-cfasync="false" src="templates/default/js/bootstrap.min.js"></script>
        <?php } ?>
    <?php } ?>

        <script data-cfasync="false" type="text/javascript" src="library/utilities/min/index.php?g=publicjs,language&amp;lang=<?php echo $this->gLanguage ?><?php echo $this->debugMinifier? '&debug=true' : '';?>&<?php echo $this->gInstalledVersion;?>"></script>
    <?php if ($this->gJSFiles != '') { ?>
        <script data-cfasync="false" type="text/javascript" src="library/utilities/min/index.php?f=<?php echo $this->gJSFiles;?><?php echo $this->debugMinifier? '&debug=true' : '';?>&ver=<?php echo $this->gInstalledVersion;?>"></script>
    <?php } ?>

    <?php if (!$this->gHideStyle) { ?>
        <script data-cfasync="false" src="<?php echo $this->templateJS['application']; ?>?ver=<?php echo $this->gInstalledVersion;?>"></script>
    <?php } ?>

    <?php if ($this->gHasAccessToLiveChat && !$this->gHideStyle) { ?>
        <script data-cfasync="false" type="text/javascript">
            var ce = ce || {};
            ce.whoisonline = {
                options: {
                    enable_location: true,
                    session_days: 5,
                    hide_chat:false,
                    location_cookie_name: 'location_ipinfodb',
                    ipinfodb_key: '7e2a309e38180caf486102979fdd93a20cb2c5603b45448630f3ad860a2802f7',
                },
                log : false
            }
           ce.protocol = window.location.protocol;
        </script>
        <script data-cfasync="false" src="plugins/dashboard/livevisitor/chat/track.php" type="text/javascript"></script>
    <?php } ?>

    <?php if ($this->maxmind_device_tracking_enabled === true) { ?>
    <script data-cfasync="false">
        maxmind_user_id = '<?php echo $this->maxmind_account_id; ?>';
        (function() {
            var loadDeviceJs = function() {
                var element = document.createElement('script');
                element.src = ('https:' == document.location.protocol ? 'https:' : 'http:') + '//device.maxmind.com/js/device.js';
                document.body.appendChild(element);
            };
            if (window.addEventListener) {
                window.addEventListener('load', loadDeviceJs, false);
            } else if (window.attachEvent) {
                window.attachEvent('onload', loadDeviceJs);
            }
        })();
    </script>
    <?php } ?>

    <?php if (!$this->gHideStyle) { ?>
        <?php echo $this->unescape($this->footerHTML); ?>
    <?php } ?>
    </body>
</html>