<div class="content-page">
    <div class="container">
        <div class="cm-holder">
            <div class="data-table-wrapper">
                <div class="head">
                    <h1>
                        <?php echo $this->user->lang('Password Reset'); ?>
                    </h1>
                </div>
                <div class="cs-padding">
                    <?php if ($this->success == 1) { ?>
                    <div class="alert alert-success" role="alert">
                        <?php echo $this->user->lang('If the email address you entered matches an existing account, an email will be sent with further instructions.'); ?>
                    </div>
                    <?php } else { ?>
                    <form method="post" action="index.php?fuse=home&action=resetpassword" class="validate-form">
                        <div class="col-lg-4 col-12 form-group">
                            <label class="control-label" for="email">
                                <?php echo $this->user->lang('Email Address'); ?>
                            </label>
                            <input data-parsley-required class="form-control" value="" type="email" id="email" name="email">
                        </div>
                        <?php if ($this->showCaptcha) { ?>
                        <div class="col-lg-5 col-12 form-group">
                            <?php echo $this->unescape($this->captchaHtml); ?>
                        </div>
                        <?php } ?>
                        <div class="col-md-5 col-12 form-group" style="clear: both">
                            <input type="submit" class="app-btns primary" value="<?php echo $this->user->lang('Submit'); ?>">
                        </div>
                    </form>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>