<style>
    ul.articles li {
        height: 50px;
    }
</style>

<div class="kb-search-form">
    <form action="index.php" method="GET" id="support-search" class="support-search-big">
        <input type="hidden" name="fuse" value="knowledgebase">
        <input type="hidden" name="controller" value="articles">
        <input type="hidden" name="view" value="search">
        <input type="hidden" name="subject" value ="">
        <div class="outer">
            <div class="inner support-search-inner input-group">
                <input type="text" id="query" name="query" maxlength="100" value="" placeholder="<?php echo $this->user->lang("Have a question? Ask or enter a search term here.");?>" class="support-search-kb form-control" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-inverse btn-default support-search-submit" style=""><span><?php echo $this->user->lang("Search");?></span></button>
                </span>
            </div>
        </div>
    </form>
</div>

<?php if ( count($this->articles) > 0 ) { ?>
<div class="alert ce-alert ce-alert-info">
    <?php echo $this->user->lang('The following articles were found:'); ?>
</div>
<ul class="articles">
    <?php foreach ( $this->articles as $article ) { ?>
    <li>
        <div class="article"></div>
        <a class="articleName" href="<?php echo $article['href']; ?>">
            <?php echo html_entity_decode($this->escape($article['title']), ENT_QUOTES); ?>
        </a>
        <br/>
            Added on <?php echo $article['created']; ?> by <?php echo $article['author']; ?>

    </li>
    <?php } ?>
</ul>
<?php } else { ?>
<div class="alert ce-alert ce-alert-error">
    <?php echo $this->user->lang('Sorry, no articles could be found.'); ?>
</div>
<?php } ?>