<form method="post" name="login" action="index.php?fuse=admin&amp;action=Login">
    <?php if ($this->showloginneededwarning) { ?>
    <div class="alert alert-danger alert-dismissible ce-alert ce-alert-error" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <b><?php echo $this->user->lang("Access denied"); ?></b><br>
        <?php echo $this->user->lang("You must login before performing that action"); ?>
    </div>
    <?php } ?>

    <div class="alert alert-success alert-dismissible ce-alert ce-alert-success alert-reset-password-success" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <?php echo $this->user->lang("An email has been sent to your account to reset your password.");?>
    </div>

    <div class="alert ce-alert ce-alert-success alert-registration-success alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <?php echo $this->user->lang("Thank you for registering. An email has been sent to your account to complete your registration."); ?>
    </div>

    <div class="col-xs-12 col-sm-6 col-xs-offset-0 col-sm-offset-3 col-md-4 col-md-offset-4">
        <div class="ce-loginbox">
            <div class="ce-loginbox-header"></div>
            <div class="alert-loginalerts alert ce-alert alert-info text-center"><?php echo $this->user->lang("You must log in to access the client area");?>.</div>
            <div class="registeredlogin">
                <h4 class="text-center"><?php echo $this->user->lang("Login using your registered account");?></h4>
                <div class="input-group col-xs-12">
                    <input type="text" name="email" class="form-control">
                    <div class="input-group-addon"><i class="fa fa-user"></i></div>
                </div>
                <div class="input-group col-xs-12">
                    <input type="password" name="passed_password" class="form-control">
                    <div class="input-group-addon"><i class="fa fa-key"></i></div>
                </div>
                <div>
                    <a class="forgotpasswordurl"><?php echo $this->user->lang("Forgot your password");?></a>
                </div>
                <div id="loginbtn" class="col-xs-12 col-xs-offset-0 col-sm-5 col-sm-offset-7">
                    <button class="btn btn-default form-control" type="submit"><?php echo $this->user->lang("Sign In");?></button>
                </div>
            <?php if ($this->allowRegistration) { ?>
                <div class="text-right">
                    <a class="newaccounturl"><?php echo $this->user->lang("Don't have an account?  Register now");?></a>
                </div>
            <?php }?>
            </div>
        </div>
    </div>

    <?php if ($this->showForgot) { ?>
    <script data-cfasync="false" type="text/javascript">
        $(document).ready(function(){
            setTimeout(function(){
                $('.forgotpasswordurl').trigger('click');
            },0);
        });
    </script>
    <?php } ?>


    <?php if ($this->allowRegistration && $this->showRegister) { ?>
    <script data-cfasync="false" type="text/javascript">
        $(document).ready(function(){
            setTimeout(function(){
                $('.newaccounturl').trigger('click');
            },0);
        });
    </script>
    <?php } ?>
</form>