<?php
$showBoxes = $this->templateOptions['Show Action Boxes']['value'];
$colors = array(
    '#113F8C',
    '#FFA601',
    '#CD321D',
    '#01A4A4',
    '#00A1CB',
    '#61AE24',
    '#006699',
    '#D0D102',
    '#32742C',
    '#D70060',
    '#E54028',
    '#F18D05',
    '#616161',
    '#71E1FF',
    '#69D6FF',
);
$color_index = 0;

$url = "order.php";
$cart_count = "";
if ($this->summary['cartCount'] > 0) {
    $url = "order.php?step=3";
    $cart_count = $this->summary['cartCount'];
}

$artcount = 1;

if ($this->user->hasPermission('knowledgebase_view')) {
    if (count($this->faqs) > 0) {
        $latestclass = "";
        $latesttabclass = "";
        $faqtabclass = "in active";
        $populartabclass = '';
        $populartabcontentclass = '';
    } elseif (!$this->showLatestArticles) {
        $latestclass = "";
        $latesttabclass = "";
        $faqtabclass = "";
        $populartabclass = 'in active';
        $populartabcontentclass = 'active';
    } else {
        $latestclass = "active";
        $latesttabclass = "in active";
        $faqtabclass = "";
        $populartabclass = '';
        $populartabcontentclass = '';
    }
}

?>

<?php if ($showBoxes == "Yes") { ?>
    <div class="support-boxes row">
        <a href="index.php?fuse=home&view=dashboard" class="support-box col-xs-12 col-sm-3">
            <div class="feature-block panel panel-default">
                <div class="panel-body">
                    <div class="feature-tab img-circle" style="background-color: <?php echo $colors[$color_index++]; ?>">
                        <i class="fa fa-cogs"></i>
                    </div>
                    <h2><?php echo $this->user->lang("Manage account");?></h2>
                    <p><?php echo $this->user->lang("Enter your account area if you are registered");?></p>
                </div>
            </div>
        </a>

    <?php if ($this->user->hasPermission('knowledgebase_view')) { ?>
        <a href="<?php echo CE_Lib::generateMainKBLink(); ?>" class="support-box col-xs-12 col-sm-3">
            <div class="feature-block panel panel-default">
                <div class="panel-body">
                    <div class="feature-tab img-circle" style="background-color: <?php echo $colors[$color_index++]; ?>">
                        <i class="fa fa-cloud"></i>
                    </div>
                    <h2><?php echo $this->user->lang("Search our KB");?></h2>
                    <p><?php echo $this->user->lang("Browse our Knowledge base by Topic or Search");?></p>
                </div>
            </div>
        </a>
    <?php } ?>

    <?php if ($this->user->hasPermission('support_submit_ticket')) { ?>
        <a href="index.php?fuse=support&controller=ticket&view=submitticket" class="support-box col-xs-12 col-sm-3">
            <div class="feature-block panel panel-default">
                <div class="panel-body">
                    <div class="feature-tab img-circle" style="background-color: <?php echo $colors[$color_index++]; ?>">
                        <i class="fa fa-ticket"></i>
                    </div>
                    <h2><?php echo $this->user->lang("Submit an issue");?></h2>
                    <p><?php echo $this->user->lang("Having a problem?  Our support staff can assist");?></p>
                </div>
            </div>
        </a>
    <?php } ?>

        <a href="<?php echo $url ;?>" class="support-box col-xs-12 col-sm-3">
            <div class="feature-block panel panel-default">
                <div class="panel-body">
                    <div class="feature-tab img-circle" style="background-color: <?php echo $colors[$color_index++]; ?>">
                        <i class="fa fa-shopping-cart"></i>
                    </div>
                    <span class="badge badge-important cart-badge"><?php echo $cart_count;?></span>
                    <h2 class="<?php echo ($cart_count !="") ? "has-cart-badge" : "" ;?>" ><?php echo $this->user->lang("Order New Service");?></h2>
                    <p><?php echo $this->user->lang("Browse the Products & Services we offer");?></p>
                </div>
            </div>
        </a>

    <?php if (count($this->snapins) > 0) { ?>
        <?php foreach ($this->snapins as $snapin) { ?>
            <?php if (isset($snapin->mapping['publicmain'])) { ?>
                <?php foreach ($snapin->mapping['publicmain'] as $hash_key => $map) { ?>
                    <?php if ($color_index > 14) { ?>
                        <?php $color_index = 0; ?>
                    <?php } ?>
        <a href="<?php echo "index.php?fuse=admin&view=snapin&controller=snapins&h=".urlencode(base64_encode("publicmain:".$hash_key))."&plugin=".$snapin->getInternalName(); ?>" class="support-box col-xs-12 col-sm-3">
            <div class="feature-block panel panel-default">
                <div class="panel-body">
                    <?php $snapin_icon_class = ($map['icon'] != "") ? $map['icon'] : "fa fa-exclamation"; ?>
                    <?php $snapin_icon_style = ($map['iconstyle'] != "") ? $map['iconstyle'] : ""; ?>
                    <div class="feature-tab img-circle" style="background-color:<?php echo $colors[$color_index++]; ?>">
                        <i class="<?php echo $snapin_icon_class;?>" style="<?php echo $snapin_icon_style;?>"></i>
                    </div>
                    <h2><?php echo substr($map['title'], 0, 20);?></h2>
                    <p><?php echo $snapin->getVariable('Public Description'); ?></p>
                </div>
            </div>
        </a>
                <?php } ?>
            <?php } ?>
        <?php } ?>
    <?php } ?>

    <!-- Show Global Series Separately -->
    <?php if ($this->show_series_name != "") { ?>
        <a href="<?php echo $this->seriesURL; ?>" class="support-box col-xs-12 col-sm-3">
            <div class="feature-block panel panel-default">
                <div class="panel-body">
                    <div class="feature-tab img-circle" style="background-color: <?php echo $colors[$color_index++]; ?>">
                        <i class="fa fa-file-text-o"></i>
                    </div>
                    <h2><?php echo $this->show_series_name;?></h2>
                    <p><?php echo $this->show_series_subname;?></p>
                </div>
            </div>
        </a>
    <?php } ?>
    </div>
<?php } ?>

<div class="main-bottom-blox">
<?php if (count($this->announcements) > 0) { ?>
    <?php for ($i = 0; $i < count($this->announcements); $i++) {?>
    <div class="announcement">
        <div class="container-fluid">
            <div class="post-date col-xs-2 col-sm-1">
                <div>
                    <div class="day"><?php echo $this->announcements[$i]['day'];?></div>
                    <div class="month"><?php echo $this->announcements[$i]['month'];?></div>
                </div>
            </div>
            <div class="announcement-title col-xs-10 col-sm-11">
                <h2 class="row">
                    <a href="index.php?fuse=home&controller=announcements&view=announcement&ann_id=<?php echo $this->announcements[$i]['annid']; ?>">
                        <?php echo $this->announcements[$i]['title']; ?>
                    </a>
                </h2>
            </div>
            <div class="announcement-meta col-xs-12 col-sm-11">
                <i class="fa fa-clock-o"></i>&nbsp;
                <?php echo $this->announcements[$i]['date'];?>&nbsp;
                <?php echo $this->user->lang("by"); ?>&nbsp;
                <?php echo $this->announcements[$i]['postedBy'];?>
            </div>
            <div class="ann-post col-xs-12">
                <?php echo $this->announcements[$i]['excerpt']; ?>
            </div>
        <?php if ($i == (count($this->announcements)-1)) { ?>
            <div class="ann-links col-xs-12">
                <a href="index.php?fuse=home&controller=announcements&view=announcements">
                    <?php echo $this->user->lang("View past announcements");?>
                </a>
            </div>
        <?php } ?>
        </div>
    </div>
    <?php } ?>
<?php } ?>
<?php if ($this->user->hasPermission('knowledgebase_view') && (count($this->faqs) > 0 || $this->showLatestArticles || count($this->populararticles) > 0)) { ?>
    <div class="hidden-xs">
        <ul class="nav nav-tabs">
        <?php if (count($this->faqs) > 0) { ?>
            <li class="active">
                <a href="#faqtab" data-toggle="tab">
                    <?php echo $this->user->lang("Frequently Asked Questions"); ?>
                </a>
            </li>
        <?php } ?>
        <?php if ($this->showLatestArticles) { ?>
            <li class="<?php echo $latestclass;?>">
                <a href="#articlestab" data-toggle="tab">
                    <?php echo $this->user->lang("Latest Articles"); ?>
                </a>
            </li>
        <?php } ?>
        <?php if (count($this->populararticles)  > 0) { ?>
            <li class="<?php echo $populartabclass ?>">
                <a href="#populartab" data-toggle="tab">
                    <?php echo $this->user->lang("Popular Articles"); ?>
                </a>
            </li>
        <?php } ?>
        </ul>
        <div class="tab-content">
        <?php if (count($this->faqs) > 0) { ?>
            <div class="tab-pane fade <?php echo $faqtabclass;?>" id="faqtab">
                <div class="panel-group" id="faq-accordion" role="tablist" aria-multiselectable="true">
                <?php foreach ($this->faqs as $faq) { ?>
                    <div class="panel panel-default">
                        <div class="panel-heading faq-accordion-heading" role="tab">
                            <h4 class="panel-title">
                                <a role="button" data-toggle="collapse" data-parent="#faq-accordion" href="#art<?php echo $faq['id'];?>" aria-expanded="true" aria-controls="art<?php echo $faq['id'];?>">
                                    <?php echo $artcount; ?>.&nbsp;&nbsp;<?php echo $faq['articlename'];?>
                                </a>
                            </h4>
                            <?php $artcount++; ?>
                        </div>
                        <div id="art<?php echo $faq['id'];?>" class="panel-collapse collapse" role="tabpanel" aria-controls="art<?php echo $faq['id'];?>">
                            <div class="panel-body">
                                <?php echo str_replace(array("../uploads/knowledgebase/", "&lt;br&gt;"), array("uploads/knowledgebase/", "<br>"), $faq['content']); ?>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                </div>
            </div>
        <?php } ?>
        <?php if ($this->showLatestArticles) { ?>
            <div class="tab-pane fade <?php echo $latesttabclass;?>" id="articlestab">
                <table class="table table-striped recent-articles ">
                <?php foreach ($this->latestarticles as $article) { ?>
                    <tr class="recent-article">
                        <td>
                            <div class="article-image">
                                <i class="fa fa-file-text-o"></i>
                            </div>
                            <div class="articleName">
                                <a href="<?php echo $article['article_link']; ?>">
                                    <?php echo $article['articleTitle']; ?>
                                </a>
                            </div>
                            <div class="articleMeta">
                                <a class="categoryName" href="<?php echo $article['category_link']; ?>">
                                    <?php echo $article['categoryName']; ?> &raquo;
                                </a>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
                </table>
            </div>
        <?php } ?>
        <?php if (count($this->populararticles)  > 0) { ?>
            <div class="tab-pane <?php echo $populartabcontentclass ?>" id="populartab">
                <table class="table table-striped recent-articles ">
                <?php foreach ($this->populararticles as $article) { ?>
                    <tr class="recent-article">
                        <td>
                            <div class="article-image">
                                <i class="fa fa-file-text-o"></i>
                            </div>
                            <div class="articleName">
                                <a href="<?php echo $article['article_link']; ?>">
                                    <?php echo $article['title']; ?>
                                </a>
                            </div>
                            <div class="articleMeta">
                                <a class="categoryName" href="<?php echo $article['category_link']; ?>">
                                    <?php echo $article['categoryname']; ?> &raquo;
                                </a>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
                </table>
            </div>
        <?php } ?>
        </div>
    </div>
    <div class="visible-xs">
        <div class="panel-group" id="kb-accordion" role="tablist" aria-multiselectable="true">
        <?php if (count($this->faqs) > 0) { ?>
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="faq-header">
                    <a role="button" data-toggle="collapse" data-parent="#kb-accordion" href="#faq-tab" aria-expanded="true" aria-controls="faq-tab">
                        <h4 class="panel-title">
                            <?php echo $this->user->lang("Frequently Asked Questions"); ?>
                        </h4>
                    </a>
                </div>
                <div id="faq-tab" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="faq-tab">
                    <div class="panel-body">
                        <div class="panel-group" id="faq2-accordion" role="tablist" aria-multiselectable="true">
                        <?php $artcount = 1; ?>
                        <?php foreach ($this->faqs as $faq) { ?>
                            <div class="panel panel-default">
                                <div class="panel-heading faq-accordion-heading" role="tab">
                                    <h4 class="panel-title">
                                        <a role="button" data-toggle="collapse" data-parent="#faq2-accordion" href="#art2-<?php echo $faq['id'];?>" aria-expanded="true" aria-controls="art2-<?php echo $faq['id'];?>">
                                            <?php echo $artcount; ?>.&nbsp;&nbsp;<?php echo $faq['articlename'];?>
                                        </a>
                                    </h4>
                                    <?php $artcount++; ?>
                                </div>
                                <div id="art2-<?php echo $faq['id'];?>" class="panel-collapse collapse" role="tabpanel" aria-controls="art2-<?php echo $faq['id'];?>">
                                    <div class="panel-body">
                                        <?php echo str_replace(array("../uploads/knowledgebase/", "&lt;br&gt;"), array("uploads/knowledgebase/", "<br>"), $faq['content']); ?>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
        <?php if ($this->showLatestArticles) { ?>
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="articles-header">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#kb-accordion" href="#articles-tab" aria-expanded="true" aria-controls="articles-tab">
                        <h4 class="panel-title">
                            <?php echo $this->user->lang("Latest Articles"); ?>
                        </h4>
                    </a>
                </div>
                <div id="articles-tab" class="panel-collapse collapse" role="tabpanel" aria-labelledby="articles-tab">
                    <table class="table table-striped recent-articles ">
                    <?php foreach ($this->latestarticles as $article) { ?>
                        <tr class="recent-article">
                            <td>
                                <div class="article-image">
                                    <i class="fa fa-file-text-o"></i>
                                </div>
                                <div class="articleName">
                                    <a href="<?php echo $article['article_link']; ?>">
                                        <?php echo $article['articleTitle']; ?>
                                    </a>
                                </div>
                                <div class="articleMeta">
                                    <a class="categoryName" href="<?php echo $article['category_link']; ?>">
                                        <?php echo $article['categoryName']; ?> &raquo;
                                    </a>
                                </div>
                            </td>
                        </tr>
                    <?php } ?>
                    </table>
                </div>
            </div>
        <?php } ?>
        <?php if (count($this->populararticles)  > 0) { ?>
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="popular-header">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#kb-accordion" href="#popular-tab" aria-expanded="true" aria-controls="popular-tab">
                        <h4 class="panel-title">
                            <?php echo $this->user->lang("Popular Articles"); ?>
                        </h4>
                    </a>
                </div>
                <div id="popular-tab" class="panel-collapse collapse" role="tabpanel" aria-labelledby="popular-tab">
                    <table class="table table-striped recent-articles ">
                    <?php foreach ($this->populararticles as $article) { ?>
                        <tr class="recent-article">
                            <td>
                                <div class="article-image">
                                    <i class="fa fa-file-text-o"></i>
                                </div>
                                <div class="articleName">
                                    <a href="<?php echo $article['article_link']; ?>">
                                        <?php echo $article['title']; ?>
                                    </a>
                                </div>
                                <div class="articleMeta">
                                    <a class="categoryName" href="<?php echo $article['category_link']; ?>">
                                        <?php echo $article['categoryname']; ?> &raquo;
                                    </a>
                                </div>
                            </td>
                        </tr>
                    <?php } ?>
                    </table>
                </div>
            </div>
        <?php } ?>
        </div>
    </div>
<?php } ?>
</div>
