<div class="alert ce-alert register-description description">
    <?php echo $this->user->lang("Reset your password by entering your registered email address below. You will receive an email shortly with instructions.");?>
</div>

<div class="col-xs-12 header form-group">
    <label><?php echo $this->user->lang("Email");?></label>
    <input type="text" class="customerEmail form-control" data-required="true" data-type="email" name="customerEmail" value="">
</div>