<div class="content-area dashboard-wraper">
    <div class="container">
        <div class="package-view-page">
            <?php echo $this->publicproductheader($this->user); ?>
            <div class="product-detail-block">
                <div class="row">
                    <?php echo $this->unescape($this->output); ?>
                </div>
            </div>
        </div>
    </div>
</div>