<?php if (!$this->hasPermission && !$this->loggedin) { ?>
    <div class="alert alert-danger ce-alert ce-alert-error">
        <?php echo $this->user->lang('Guest ticket access is disabled, please '); ?>
        <a href='index.php?fuse=home&view=login'>
            <?php echo $this->user->lang('login'); ?>
        </a>
    </div>
    <?php return; ?>
<?php } ?>

<?php if ($this->user->isAdmin()) { ?>
    <div class="alert alert-danger ce-alert ce-alert-error">
        <?php echo $this->user->lang('You are currently logged in as an administrator.  Please log out of the administration panel before attempting to submit a support ticket.'); ?>
    </div>
    <?php return; ?>
<?php } ?>

<form method="post" enctype="multipart/form-data" action="index.php?fuse=support&controller=ticket&action=saveticket" class="support-ticket-form">
    <input type="hidden" name="userid" value="<?php echo $this->user->getId(); ?>">
<?php if (isset($this->clientid)) { ?>
    <input type="hidden" name="clientid" value="<?php echo $this->clientid; ?>">
<?php } ?>

    <div class="form-group col-xs-12 col-sm-6">
        <label for="ticket-type" class="control-label">
            <?php echo $this->user->lang("What can we assist you with?");?>
        </label>
        <select name="ticket-type" class="drop-ticket-type form-control selectpicker" data-live-search="true" title="<?php echo $this->user->lang("Select below ...");?>">
        <?php foreach ($this->tickettypes as $ticketType) { ?>
            <option value="<?php echo $ticketType['value']; ?>" <?php echo $ticketType['selected']; ?>>
                <?php echo $ticketType['name'];?>
            </option>
        <?php } ?>
        </select>
    </div>

    <div class="top-questions-block col-xs-12">
        <h1 class="review-questions-header"><?php echo $this->user->lang("Review top questions for");?> <span class="review-questions-fortype"></span></h1>
        <div class='review-questions-desc'><?php echo $this->user->lang("Top questions asked for the selected issue type."); ?></div>
    </div>

    <h1 class="file-ticket-header col-xs-12"><?php echo $this->user->lang("File a ticket");?></h1>
    <div class="file-ticket-desc col-xs-12">
        <?php echo $this->user->lang("If you can not find a solution to your issue in our <a href=\"index.php?fuse=knowledgebase&controller=articles&view=main\">knowledgebase</a>, please submit your question below."); ?>
    </div>

<?php if (isset($this->domainDropDown)) { ?>
    <div class="form-group col-xs-12">
        <label class="control-label"><?php echo $this->user->lang("What package is this in reference to?"); ?></label>
        <?php echo $this->unescape($this->domainDropDown); ?>
    </div>
<?php } ?>

    <div class="form-group col-xs-12 col-sm-6">
        <label for="subject" class="control-label"><?php echo $this->user->lang("Subject");?></label>
        <input type="text" dir="auto" onkeyup="<?php echo $this->subjectOnkeyup; ?>" name="subject" class="ticket-subject form-control" data-required="true" value="<?php echo $this->subject;?>">
        <div class="subject-article-matches"></div>
    </div>

    <div class="form-group col-xs-12">
        <label for="message" class="control-label"><?php echo $this->user->lang("Question");?></label>
        <textarea rows="10" dir="auto" class="support-ticket-message ticket-align form-control" name="message" data-required="true"><?php echo $this->message;?></textarea>
    </div>

<?php if ($this->maxfilesize > 0 && $this->extns) { ?>
    <div class="form-group col-xs-12">
        <div class="share-upload-desc">
            <?php echo $this->user->lang("Sharing a picture will help us understand your question even more.");?>. <?php echo $this->user->lang("Max file size");?>: <?php echo $this->maxfilesize; ?>
        <?php if ($this->extns != '*') { ?>
            - <a href="#" data-toggle="tooltip" data-placement="top" title="<h4><?php echo $this->user->lang("Allowed file extensions");?></h4><p><?php echo $this->extnsmessage; ?></p>"><?php echo $this->user->lang('See Allowed Extensions') ?></a>
        <?php } ?>
        </div>
        <div id="fileFieldsContainer" class="col-xs-12 form-actions">
            <div id="fileFields_0" class="hidden file-upload col-xs-12 col-sm-7">
                <label class="btn btn-default btn-file col-xs-12 col-sm-4">
                    <?php echo $this->user->lang("Choose File");?> <input class="file_upload_input" id="file_0" name="file_0" type="file">
                </label>
                <a class="hidden btn btn-danger col-xs-6 col-sm-3"><?php echo $this->user->lang('Delete') ?></a>
            </div>
        </div>
        <a id="new-file-button" class="btn btn-success col-xs-12 col-sm-2" href="#"><?php echo $this->user->lang('Add a New File') ?></a>
        <input type="hidden" name="validExtns" value="<?php echo $this->extns; ?>" />
    </div>
<?php } //attach file ?>

<?php if ($this->user->getId() ==0) { ?>
    <div class="form-group col-xs-12 col-sm-6">
        <label for="guestName"><?php echo $this->user->lang("Full Name");?></label>
        <input class="form-control" data-required="true" type="text" id="guestName" name="guestName" placeholder="<?php echo $this->user->lang("First and Last Name");?>" value="<?php echo $this->guestname; ?>" />
    </div>
    <div class="form-group col-xs-12 col-sm-6">
        <label for="guestEmail"><?php echo $this->user->lang("Email");?></label>
        <input class="form-control" data-required="true" data-type="email" type="text" id="guestEmail" name="guestEmail" placeholder="<?php echo $this->user->lang("Your Email");?>" value="<?php echo $this->guestemail; ?>" />
    </div>
<?php } //end guest info ?>

    <div class="form-group fieldset-customfields col-xs-12 hidden">
        <h1 class="customfields-header"><?php echo $this->user->lang("Additional information that may assist us");?></h1>
        <div class="customfields customfields-wrapper"></div>
    </div>

<?php if ($this->showCaptcha) { ?>
    <div class="form-group col-xs-12">
        <div class="g-recaptcha" data-sitekey="<?php echo $this->captchaPublicKey; ?>"></div>
        <script type="text/javascript" src="https://www.google.com/recaptcha/api.js"></script>
    </div>
<?php } ?>

    <div class="col-xs-12">
        <div class="well col-xs-12">
            <div class="col-xs-12 col-xs-offset-0 col-sm-2 col-sm-offset-10">
                <button type="submit" class="form-control btn btn-newticket-submit btn-default"><?php echo $this->user->lang("Submit Ticket");?></button>
            </div>
        </div>
    </div>
    <div class="spacer-bottom"></div>
</form>

<script type="text/html" id="articles">
    <table class='table table-striped table-hover'>
        <tbody>
            {{#articles}}
                <tr>
                    <td>{{#categoryname}}<a href="index.php?fuse=knowledgebase&controller=articles&view=main&categoryId={{categoryid}}"><span class="label label-important">{{categoryname}}</span></a>&nbsp&nbsp{{/categoryname}}<a href='index.php?fuse=knowledgebase&view=article&controller=articles&articleId={{id}}'>{{title}}</a>
                    </td>
                </tr>
            {{/articles}}
        </tbody>
    </table>
</script>
