<script data-cfasync="false" type="text/javascript">
    invoices = {};
    invoices.payment_method = "<?php echo $this->payment_method;?>";
    invoices.filter = '<?php echo $this->filter; ?>';
</script>

<?php if ($this->show_change_of_billing_options) { ?>
<div class="alert alert-info ce-alert ce-alert-info">
    <?php if ($this->accepts_cc && !$this->cc_added) { ?>
        <p><?php echo $this->user->lang("You have not selected a payment method").". ".$this->user->lang("For any modifications please visit your ")."<a href='index.php?fuse=clients&controller=userprofile&view=paymentmethod'>".$this->user->lang("payment configuration page.")."</a> ".$this->user->lang("Keeping your payment options up to date will prevent any service disruption.");?></p>
    <?php } else { ?>
        <p><?php echo $this->user->lang("Your default payment source is set to")." ".$this->payment_type_name.". ".$this->user->lang("For any modifications please visit your ")."<a href='index.php?fuse=clients&controller=userprofile&view=paymentmethod'>".$this->user->lang("payment configuration page.")."</a> ".$this->user->lang("Keeping your payment options up to date will prevent any service disruption.");?></p>
    <?php } ?>
</div>
<?php } ?>

<div class="form-group col-xs-12">
    <div class="btn-group pull-right" role="group" id="filter-ul">
        <button type="button" class="btn<?php echo ($this->filter == 'open') ? ' btn-primary' : ''; ?>" data-filter="open">
            <?php echo $this->user->lang("Unpaid");?>
        </button>
        <button type="button" class="btn<?php echo ($this->filter == 'paid') ? ' btn-primary' : ''; ?>" data-filter="paid">
            <?php echo $this->user->lang("Paid");?>
        </button>
    <?php if ($this->hasDraftInvoices) { ?>
        <button type="button" class="btn<?php echo ($this->filter == 'draft') ? ' btn-primary' : ''; ?>" data-filter="draft">
            <?php echo $this->user->lang("Draft");?>
        </button>
    <?php } ?>
        <button type="button" class="btn<?php echo ($this->filter == 'all') ? ' btn-primary' : ''; ?>" data-filter="all">
            <?php echo $this->user->lang("All");?>
        </button>
    </div>
</div>

<div class="form-group col-xs-12">
    <div class="table-responsive">
        <table id="invoices-grid" class="table table-striped">
            <thead>
                <tr>
                    <th class="all"><input type="checkbox" id="check-all-boxes"></th>
                    <th class="all">#</th>
                    <th class="all"><?php echo $this->user->lang('Description'); ?></th>
                    <th class="all"><?php echo $this->user->lang('Due Date'); ?></th>
                    <th class="all"><?php echo $this->user->lang('Due'); ?></th>
                    <th class="all"><?php echo $this->user->lang('Total'); ?></th>
                    <th class="all"><?php echo $this->user->lang('Status'); ?></th>
                </tr>
            </thead>
        </table>
    </div>
    <div>
    <div class="row invoice-buttons">
<?php if ($this->user->hasPermission('billing_send_invoices')) { ?>
        <div class="col-xs-12 col-sm-2">
            <div class="row">
                <button type="button" class="btn btn-default btn-lg form-control" data-toggle="modal" data-target="#confirmSendInvoice" id="openConfirmInvoices">
                    <?php echo $this->user->lang("Send Invoice(s)"); ?>
                </button>
            </div>
        </div>
<?php } ?>
<?php if ($this->user->hasPermission('billing_masspay')) { ?>
        <div class="col-xs-12 col-sm-2">
            <button type="button" class="btn btn-default btn-lg form-control" id="massPayButton">
                <?php echo $this->user->lang("Mass Pay"); ?>
            </button>
        </div>
<?php } ?>
    </div>
</div>
<div class="hidden" id="invoices-hidden"></div>
<div class="modal fade" tabindex="-1" role="dialog" id="confirmSendInvoice">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <h4><?php echo $this->user->lang('Are you sure you want to send the selected invoice(s)?'); ?></h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal"><?php echo $this->user->lang('No'); ?></button>
                <button type="button" class="btn btn-success" id="sendInvoice"><?php echo $this->user->lang('Yes'); ?></button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" tabindex="-1" role="dialog" id="feedback">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <h4><?php echo $this->user->lang('Invoices have been successfully sent'); ?></h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal"><?php echo $this->user->lang('Ok'); ?></button>
            </div>
        </div>
    </div>
</div>