<div class="content-area knowledge-base-wraper">
    <div class="container">
        <div class="knowledge-base-search2">
            <div class="knowledge-base-search-box2">
                <h1>
                    <?php echo $this->user->lang('Knowledge Base'); ?>
                </h1>
                <div class="knowledge-search-box">
                    <form action="index.php" method="GET" id="support-search" class="support-search-big">
                        <input type="hidden" name="fuse" value="knowledgebase">
                        <input type="hidden" name="controller" value="articles">
                        <input type="hidden" name="view" value="search">
                        <input name="subject" type="text" class="knowledge-search-input" placeholder="<?php echo $this->user->lang('Enter your question'); ?>">
                        <input type="submit" class="knowledge-search-submit" value="">
                    </form>
                </div>
                <p>
                 <?php
                    echo $this->user->lang(
                        "Can't find what you're looking for? %sCreate a ticket.%s",
                        '<a href="index.php?fuse=support&controller=ticket&view=submitticket">',
                        '</a>'
                    );
                ?>
                </p>
            </div>
        </div>
        <?php if ( count($this->articles) > 0 ) { ?>
        <div class="knowledge-base-boxes-block">
            <div class="row">
                <div class="col-lg-12 col-md-6-12">
                    <div class="knowledge-base-box search-results">
                        <h4>
                            <?php echo $this->user->lang('Search results for: %s', $this->searchText); ?>
                        </h4>
                        <ul class="knowledge-box-ul open">
                            <?php foreach ( $this->articles as $article ) { ?>
                            <li>
                                <a class="articleName" href="<?php echo $article['href']; ?>">
                                    <?php echo html_entity_decode($this->escape($article['title']), ENT_QUOTES); ?>
                                </a>
                            </li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <?php } else { ?>
        <div class="knowledge-base-boxes-block">
            <div class="row">
                <div class="col-lg-12 col-md-6-12">
                    <div class="knowledge-base-box search-results">
                        <h4>
                            <?php
                                    echo $this->user->lang('No search results for: %s', $this->searchText);
                            ?>
                        </h4>
                        <ul class="knowledge-box-ul no-results">
                            <li>
                                <?php echo $this->user->lang(
                                    'Try another search term or contact us by %screating a ticket.%s',
                                    '<a class="open-ticket" href="index.php?fuse=support&controller=ticket&view=submitticket">',
                                    '</a>');
                                ?>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <?php } ?>
    </div>
</div>