<div class="content-page">
    <div class="container">
        <div class="cm-holder">
            <div class="data-table-wrapper">
                <div class="head">
                    <h1>
                        <?php echo $this->user->lang('Change Password'); ?>
                    </h1>
                </div>
                <div class="cs-padding">
                    <form method="post" action="index.php?fuse=clients&controller=userprofile&action=updatepassword" id="update-password-form" class="validate-form">
                        <div class="col-md-5 col-12 form-group">
                            <label class="control-label" for="password">
                                <?php echo $this->user->lang('Existing Password'); ?></label>
                            <input class="form-control" value="" type="password" id="password" name="password" required>
                        </div>
                        <div class="col-md-5 col-12 form-group" style="clear: both">
                            <label class="control-label" for="new-password">
                                <?php echo $this->user->lang('New Password'); ?></label>
                            <input data-parsley-equalto="#confirm-password" class="form-control" value="" type="password" id="new-password" name="new-password" required>
                        </div>
                        <div class="col-md-5 col-12 form-group" style="clear: both">
                            <label class="control-label" for="confirm-password">
                                <?php echo $this->user->lang('Confirm New Password'); ?></label>
                            <input class="form-control" value="" type="password" id="confirm-password" name="confirm-password" required data-parsley-equalto="#new-password">
                        </div>
                        <div class="col-md-5 col-12 form-group" style="clear: both">
                            <input type="submit" class="app-btns primary" value="<?php echo $this->user->lang('Update'); ?>">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>