<h1 class="pull-left"><?php echo $this->user->lang("Alternate Accounts");?></h1>

<form method="post" action="index.php?fuse=clients&action=updatealtemail&controller=userprofile" >
    <table class="table ce-table table-striped table-hover table-responsive text-center">
        <thead>
            <tr>
                <th class="text-center"><?php echo $this->user->lang('Email'); ?></th>
                <th class="text-center"><?php echo $this->user->lang('Notifications'); ?></th>
                <th class="text-center"><?php echo $this->user->lang('Invoices'); ?></th>
                <th class="text-center"><?php echo $this->user->lang('Support'); ?></th>
                <th class="text-center"><?php echo $this->user->lang('Delete'); ?></th>
            </tr>
        </thead>

        <?php foreach ($this->accounts as $account) { ?>
        <tr>
            <td><input class="form-control" type="text" name="email_<?php echo $account['altEmailId']; ?>" value="<?php echo $account['altEmail']; ?>"></td>
            <td><input type="checkbox" name="sendnotifications_<?php echo $account['altEmailId']; ?>" <?php echo $account['sendNotifications']; ?>></td>
            <td><input type="checkbox" name="sendinvoice_<?php echo $account['altEmailId']; ?>" <?php echo $account['sendInvoice']; ?>></td>
            <td><input type="checkbox" name="sendsupport_<?php echo $account['altEmailId']; ?>" <?php echo $account['support']; ?>></td>
            <td><input type="checkbox" name="delete_<?php echo $account['altEmailId']; ?>"></td>
        </tr>
        <?php } ?>

        <tr>
            <td><input type="text" class="form-control" name="newaltemail"></td>
            <td><input type="checkbox" name="newnotify"></td>
            <td><input type="checkbox" name="newinvoice"></td>
            <td><input type="checkbox" name="newsupport"></td>
            <td>&nbsp;</td>
        </tr>

    </table>
    <div class="form-actions">
      <button type="submit" class="pull-right btn btn-default"><?php echo $this->user->lang('Update'); ?></button>
    </div>
</form>