<h1><?php echo $this->user->lang('Change Password'); ?></h1>

<form method="post" action="index.php?fuse=clients&controller=userprofile&action=updatepassword" id="update-password-form">
    <div class="col-sm-5 col-xs-12 form-group">
        <label class="control-label" for="password"><?php echo $this->user->lang('Existing Password'); ?></label>
        <input class="form-control" value="" type="password" id="password" name="password" data-required="true">
    </div>

    <div class="col-sm-5 col-xs-12 form-group" style="clear: both">
        <label class="control-label" for="new-password"><?php echo $this->user->lang('New Password'); ?></label>
        <input class="form-control" value="" type="password" id="new-password" name="new-password" data-required="true">
    </div>

    <div class="col-sm-5 col-xs-12 form-group" style="clear: both">
        <label class="control-label" for="confirm-password"><?php echo $this->user->lang('Confirm New Password'); ?></label>
        <input class="form-control" value="" type="password" id="confirm-password" name="confirm-password" data-required="true">
    </div>

    <div class="col-sm-5 col-xs-12 form-group" style="clear: both">
        <button style="margin-left:0px;cursor:pointer;" class="btn btn-primary" id="update-password-button">
            <?php echo $this->user->lang('Update'); ?>
        </button>
    </div>
</form>