<script data-cfasync="false" type="text/javascript" language="javascript">
    // <![CDATA[
    //keep track of what customer's old value for paypal subscription
    //was so that we can show the proper warning when updating
    paymentmethod = {};
    paymentmethod.selectedplugin='<?php echo $this->selectedpluginname; ?>';
    paymentmethod.selectedpluginrealname='<?php echo $this->selectedpluginrealname; ?>';
    // ]]>
</script>

<h1><?php echo $this->user->lang("Edit Your Payment Method");?></h1>

<form action="index.php?fuse=clients&controller=userprofile&action=updatepaymentmethod" class="update-payment-method-frm"  id="billingform" name="billingform" method="post">
    <input type="hidden" name="old_selectedplugin" class="old_selectedplugin" value="<?php echo $this->selectedpluginname; ?>" />

    <div class="form-group col-xs-12">
        <div class="col-xs-12 col-sm-4">
            <label><?php echo $this->user->lang("Payment Type");?></label>
            <select<?php echo (!$this->canEditPaymentType) ? ' readonly="readonly"' : ''; ?> class="paymenttype-list selectpicker form-control" name="paymenttype">
            <?php foreach ($this->paymentmethods as $paymentmethod) { ?>
                <option value="<?php echo $paymentmethod['paymentTypeOptionValue']; ?>" <?php echo $paymentmethod['paymentTypeOptionSelected']; ?>>
                    <?php echo $paymentmethod['paymentTypeOptionLabel']; ?>
                </option>
            <?php } ?>
            </select>
        </div>
    </div>


    <div class="alert alert-info ce-alert ce-alert-info plugin_description hidden container-fluid"></div>

    <div id="use_recurring" class="hidden container-fluid">
        <div class="alert ce-alert ce-alert-danger ce-recurring-warning col-xs-12">
          <p><b><?php echo $this->user->lang("3rd party subscription");?></b><br/><?php echo $this->user->lang("Your selected payment method is set to start a subscription after payment of your first invoice.");?></p>
        </div>
    </div>

    <div class='form-group col-xs-12 DivBillingProfileID' id='DivBillingProfileID' style='display:none'>
        <div class="col-xs-12 col-sm-4">
            <?php
                foreach ($this->profile_id_array as $paymenttype => $profile_id) {
            ?>
                <span class='BillingProfileID <?php echo $paymenttype."BillingProfileID"; ?>' id='<?php echo $paymenttype."BillingProfileID"; ?>' style='display:none'></span>
            <?php } ?>

            <?php if ($this->canEditCreditCard) { ?>
                <a class="btn btn-small btn-danger" id='btnDeleteProfileID'><span class='buttontext'>Delete Information</span></a>
                <input type='hidden' class='selected_paymenttype' id='selected_paymenttype' value="<?php echo $this->selectedpluginname; ?>" />
            <?php } ?>
        </div>
    </div>

    <?php foreach ($this->gatewayIframes as $gatewayName => $gatewayIframeConfiguration) { ?>
    <div class="container-fluid">
        <div class="col-xs-12 col-sm-6 hidden PaymentInformation <?php echo $gatewayName."PaymentInformation"; ?>" id="<?php echo $gatewayName."PaymentInformation"; ?>">
            <label><?php echo $this->user->lang("We do not store credit card information for your selected payment type"); ?></label><br/><br/>
            <iframe class="col-xs-12 PaymentIframe <?php echo $gatewayName."PaymentIframe"; ?>" id="<?php echo $gatewayName."PaymentIframe"; ?>" src ="" <?php echo $gatewayIframeConfiguration; ?> >
                <p><?php echo $this->user->lang("Your bcontainer-fluidser does not support iframes"); ?></p>
            </iframe>
        </div>
    </div>
    <?php } ?>

    <?php foreach ($this->gatewayForms as $gatewayName => $gatewayForm) { ?>
    <div class="container-fluid">
        <div class="col-xs-12 col-sm-6 hidden PaymentInformation <?php echo $gatewayName."PaymentInformation"; ?>" id="<?php echo $gatewayName."PaymentInformation"; ?>">
            <label><?php echo $this->user->lang("We do not store credit card information for your selected payment type"); ?></label><br/><br/>
            <?php echo $this->unescape($gatewayForm); ?>
        </div>
    </div>
    <?php } ?>

    <div id="creditcardinfo" class="hidden">
    <?php if ($this->canEditCreditCard) { ?>
        <div class="form-group container-fluid">
            <label class="col-xs-12"><?php echo $this->user->lang("Credit Card Number"); ?></label>
            <div id="lastfourspan" class="container-fluid">
                <div class="form-group col-xs-12 col-sm-4">
                    <input type="text" id="lastfour" name="ccnumber" size="30" disabled class="form-control">
                </div>
            </div>
            <div id="awaitingvalidationspan" class="container-fluid">
                <div class="form-group col-xs-12 col-sm-4">
                    <h4><span class="label ce-label label-info" id="awaitingvalidation"></span></h4>
                </div>
            </div>
            <div id="deleteccspan" class="container-fluid">
                <div class="form-group col-xs-12 col-sm-4">
                    <input type="button" class="btn btn-small btn-danger" id="deleteccbutton" value="<?php echo $this->user->lang("Delete Credit Card");?>">
                </div>
            </div>
            <div id="ccnumberspan" class="container-fluid">
                <div class="form-group col-xs-12 col-sm-4">
                    <input type="text" data-required="true" id="ccnumber" name="ccnumber" parsley-luhn="true" data-luhn="true" size="30" class="form-control">
                </div>
            </div>
            <div id="newccspan" class="container-fluid">
                <label class="col-xs-12">
                    <span data-toggle="tooltip" data-trigger="hover" data-placement="right" data-title="<?php echo $this->helpCCChange; ?>" class="tip-target new-card-info">
                        <?php echo $this->user->lang("New Credit Card Number"); ?>
                    </span>
                </label>
                <div class="form-group col-xs-12 col-sm-4">
                    <input type="text" id="newccnumber" name="newccnumber" parsley-luhn="true" data-luhn="true" class="form-control">
                </div>
            </div>
        </div>
        <div class="form-group container-fluid">
            <label class="col-xs-12"><?php echo $this->user->lang("Credit Card Expiration Date"); ?></label>
            <div class="col-xs-6 col-sm-2">
                <select id="ccmonth" name="ccmonth" class="selectpicker form-control">
                <?php foreach ($this->months as $month) { ?>
                    <option value="<?php echo $month['monthOptionsValue']; ?>" <?php echo $month['monthOptionsSelected']; ?> ><?php echo $month['monthOptionsLabel']; ?></option>
                <?php } ?>
                </select>
            </div>
            <div class="col-xs-6 col-sm-2">
                <select id="ccyear" name="ccyear" class="selectpicker form-control">
                <?php foreach ($this->years as $year) { ?>
                    <option value="<?php echo $year['yearOptionsValue']; ?>" <?php echo $year['yearOptionsSelected']; ?> ><?php echo $year['yearOptionsLabel']; ?></option>
                <?php } //end years ?>
                </select>
            </div>
        </div>
        <div class="form-group container-fluid">
            <label class="col-xs-12"><?php echo $this->user->lang("Accepted Credit Cards"); ?></label>
            <div class="col-xs-12">
                <img src="images/creditcards/visa.gif" id="visa_logo" alt="" />
                <img src="images/creditcards/mc.gif" id="mastercard_logo" alt="" />
                <img src="images/creditcards/amex1.gif" id="americanexpress_logo" alt="" />
                <img src="images/creditcards/discover.gif" id="discover_logo" alt="" />

                <img src="images/creditcards/laser.gif" id="lasercard_logo" alt="" />
                <img src="images/creditcards/diners.gif" id="dinersclub_logo" alt="" />
                <img src="images/creditcards/switch.gif" id="switch_logo" alt="" />
                <input type="hidden" name="validcc" id="validccbits" value='' />
            </div>
        </div>
    <?php } else { ?>
        <table class="ts2" cellspacing="0">
            <tr>
                <td class="label"><?php echo $this->user->lang("Credit Card Number"); ?>:</td>
                <td>
                    <span id="lastfourspan">
                        <span id="lastfour2"></span>
                    </span>
                    <span id="awaitingvalidationspan">
                        <span id="awaitingvalidation"></span>
                        <br />
                        <br />
                    </span>
                    <span id="ccnumberspan">
                        <input type=hidden name=c_ccnumber value="<?php echo $this->requiredMsg; ?>" />
                        <input type=hidden name=r_ccnumber value="<?php echo $this->ccRequiredMsg; ?>" />
                    </span>
                    <span id="newccspan"></span>
                </td>
            </tr>
        </table>
    <?php } //edit credit card ifs ?>
    </div>

    <div class="container-fluid">
        <div class="container-fluid">
            <div class="hidden form-actions form-group col-xs-12 col-sm-4" id="btnupdatepaymentmethod">
                <button class="btn btn-default btn-update-payment-method form-control" type="button"><?php echo $this->user->lang("Update Payment Method");?></button>
            </div>
        </div>
    </div>
</form>
