<div class="alert alert-info ce-alert ce-alert-info">
    <?php echo $this->user->lang('Requesting cancellation for: %s', $this->packageName); ?>
</div>

<div class="well well-lg">
    <form id="cancel-form" action="index.php?fuse=clients&controller=products&action=requestcancellation" method="POST">
        <input type="hidden" name="id" value="<?php echo $this->packageId; ?>" />

        <div class="form-group">
            <label><?php echo $this->user->lang('Please describe your reason for this cancellation request'); ?>:</label>
            <textarea data-required="true" name="reason" rows='10' class="form-control"></textarea>
        </div>

        <div class="form-group">
            <label><?php echo $this->user->lang('Cancellation Type'); ?>:</label>
            <select name="type" id="type" class="selectpicker">
                <option value="<?php echo PACKAGE_CANCELLATION_TYPE_IMMEDIATE; ?>"><?php echo $this->user->lang('Immediate'); ?></option>
                <?php if ($this->paidInvoicesCount > 0) { ?>
                <option value="<?php echo PACKAGE_CANCELLATION_TYPE_END_BILLING; ?>"><?php echo $this->user->lang('End of Billing Period'); ?> (<?php echo $this->endOfBillingPeriod; ?>)</option>
                <?php } ?>
            </select>
        </div>

        <div class="form-group">
            <input id="submit-button" type="submit" value="<?php echo $this->user->lang('Submit'); ?>" class="btn btn-danger" />
            <input id="cancel-button" type="button" value="<?php echo $this->user->lang('Cancel'); ?>" class="btn" />
        </div>
    </form>
</div>