<?php echo $this->publicproductheader($this->user); ?>
<div class="well well-lg col-xs-12">
    <?php if ( $this->domainNotRegistered == true ) { ?>
    <div class="alert alert-danger ce-alert ce-alert-error no-addons-text">
        <?php echo $this->user->lang("This domain currently isn't registered.");?>
    </div>
    <?php } ?>

    <?php if ( $this->hostRecordsNotSupported == true ) { ?>
    <div class="alert alert-danger ce-alert ce-alert-error no-addons-text">
        <?php echo $this->user->lang("Managing host records is not supported.");?>
    </div>
    <?php } ?>

    <?php if ( $this->domainNotActive == true ) { ?>
    <div class="alert alert-danger ce-alert ce-alert-error no-addons-text">
        <?php echo $this->user->lang("This domain currently isn't active.");?>
    </div>
    <?php } ?>

    <?php // Check if >1 because we always have the default record ?>
    <?php if ( count($this->hostRecords) > 1 ) { ?>
    <form id="hostinfo" class="col-xs-12 row">
        <input type="hidden" name="id" value="<?php echo $this->packageId; ?>" />
        <div id="hostinfo-div" class="col-xs-12 row"></div>
    <?php if ( $this->user->hasPermission('domains_updatedns') ) { ?>
        <div class="form-group col-xs-12">
            <div class="form-actions container-fluid hidden">
                <button id="update-button" class="btn btn-default btn-update-payment-method" type="button">
                    <?php echo $this->user->lang('Update Hosts'); ?>
                </button>
            </div>
        </div>
    <?php } ?>
    </form>
    <script data-cfasync="false" type="text/javascript">
        var hostinfo = {};
        hostinfo.jsonFields = <?php echo json_encode($this->hostRecords); ?>;
    </script>
    <?php } else { ?>
    <script data-cfasync="false" type="text/javascript">
        var hostinfo = {};
        hostinfo.jsonFields = <?php echo json_encode(''); ?>;
    </script>
    <?php } ?>
</div>