<?php echo $this->publicproductheader($this->user); ?>
<div class="well well-lg col-xs-12">
    <?php if ( $this->domainNotRegistered == true ) { ?>
    <div class="alert alert-danger ce-alert ce-alert-error no-addons-text">
        <?php echo $this->user->lang("This domain currently isn't registered.");?>
    </div>
    <?php } ?>

    <?php if ( $this->domainNotActive == true ) { ?>
    <div class="alert alert-danger ce-alert ce-alert-error no-addons-text">
        <?php echo $this->user->lang("This domain currently isn't active.");?>
    </div>
    <?php } ?>

    <?php if ( count($this->contactInformation) > 0 ) { ?>
    <form id="contactinfo">
        <input type="hidden" name="id" value="<?php echo $this->packageId; ?>" />
        <div id="contactinfo-div" class="form-group col-xs-12"></div>
    <?php if ($this->user->hasPermission('domains_updatecontactinfo')) { ?>
        <div class="form-group col-xs-12">
            <div class="form-actions container-fluid hidden">
                <button id="update-button" class="btn btn-default btn-update-payment-method" type="button">Update Contact Information</button>
            </div>
        </div>
    <?php } ?>
    </form>
    <script data-cfasync="false" type="text/javascript">
        var contactinfo = {};
        contactinfo.jsonFields = <?php echo json_encode($this->contactInformation); ?>;
    </script>
    <?php } ?>
</div>