<?php echo $this->publicproductheader($this->user); ?>

<?php if ( $this->domainNotRegistered == true ) { ?>
<div class="alert alert-danger ce-alert ce-alert-error no-addons-text">
    <?php echo $this->user->lang("This domain currently isn't registered.");?>
</div>
<?php } ?>

<?php if ( $this->domainNotActive == true ) { ?>
<div class="alert alert-danger ce-alert ce-alert-error no-addons-text">
    <?php echo $this->user->lang("This domain currently isn't active.");?>
</div>
<?php } ?>

<div class="well well-lg col-xs-12">
<?php if ( count($this->nameservers) > 0 ) { ?>
    <form id="nameservers">
        <input type="hidden" name="id" value="<?php echo $this->packageId; ?>" />
        <div id="nameservers-div"></div>
    <?php if ( $this->user->hasPermission('domains_editns') ) { ?>
        <div class="form-group col-xs-12">
            <div class="form-actions hidden container-fluid">
                <button id="update-button" class="btn btn-default btn-update-payment-method" type="button">
                    <?php echo $this->user->lang('Update Name Servers'); ?>
                </button>
            </div>
        </div>
    <?php } ?>
    </form>
    <script data-cfasync="false" type="text/javascript">
        var nameservers = {};
        nameservers.jsonFields = <?php echo json_encode($this->nameservers); ?>;
    </script>
<?php } ?>
</div>