<script data-cfasync="false" type="text/javascript">
      var currency = {};
      currency.symbol = '<?php echo $this->currency["symbol"]; ?>';
      currency.decimalssep = "<?php echo $this->currency['decimalssep']; ?>";
      currency.thousandssep = "<?php echo $this->currency['thousandssep']; ?>";
      currency.alignment = "<?php echo $this->currency['alignment']; ?>";
      currency.precision = "<?php echo $this->currency['precision']; ?>";
      currency.abrv = "<?php echo $this->currency['abrv']; ?>";
      currency.showabrv = "<?php echo $this->currency['showabrv']; ?>";
</script>

<div class="alert alert-info ce-alert ce-alert-info">
    <?php echo $this->user->lang('Requesting upgrade/downgrade for: %s', $this->packageName); ?>
</div>

<div class="alert alert-info ce-alert ce-alert-info">
    <?php echo $this->upgradeDowngradeStatus['upgradeMessage']; ?>
</div>

<div class="">
    <form id="upgrade-form" action="index.php?fuse=clients&controller=products&action=requestupgrade" method="POST">
        <input type="hidden" name="id" value="<?php echo $this->packageId; ?>" />
        <input type="hidden" name="customerTax" value="<?php echo $this->customerTax; ?>" />
        <input type="hidden" name="customerTax2" value="<?php echo $this->customerTax2; ?>" />
        <input type="hidden" name="customerTax2Compound" value="<?php echo $this->customerTax2Compound; ?>" />
        <input type="hidden" name="upgradeDowngradeStatusValue" value="<?php echo $this->upgradeDowngradeStatus['upgradeValue']; ?>" />

        <div class="form-group">
            <label><strong><?php echo $this->user->lang('Upgrade To Product'); ?>:</strong></label>
            <br />
            <select name="upgradePackage" id="upgradePackage" class="selectpicker" onChange="loadTotalsInfo();" >
                <?php foreach($this->upgradePackages as $package) { ?>
                    <option value="<?php echo $package["id"]; ?>" data-taxable="<?php echo $package['taxable']; ?>"><?php echo $this->user->lang($package["plannamelanguage"]); ?></option>
                <?php } ?>
            </select>
        </div>

        <?php $firstPackageId = false; ?>
        <?php $firstPackageTerm = array(); ?>
        <?php $packageStyle = ''; ?>
        <?php foreach($this->upgradePackages as $package) { ?>
            <div id="upgradePackageDescription_<?php echo $package["id"]; ?>" class="form-group upgradePackageDescription" <?php echo $packageStyle; ?> >
                <?php echo $package["descriptionlanguage"]; ?>

                <div class="panel panel-default">
                    <div class="panel-heading"><strong><?php echo $this->user->lang('Choose your Billing Term'); ?></strong></div>
                    <table class="table ce-table table-striped table-hover pricing-options table-responsive">
                        <thead>
                            <tr class="caption">
                                <th class="text-center" width="15"></th>
                                <th class="text-center" width="300"><?php echo $this->user->lang("Term Length");?></th>
                                <th class="text-center"><?php echo $this->user->lang("Renewal Price");?></th>
                                <?php if (!$this->hideSetupFees) { ?>
                                    <th class="text-right"><?php echo $this->user->lang("Setup Fee");?></th>
                                <?php } ?>
                                <th class="text-right" <?php if (!$this->showSaved) {?>style="display:none"<?php } ?>><?php if($this->showSaved) { echo $this->user->lang("You Save");}?></th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($package['pricing'] as $pricing) { ?>
                            <?php if (!isset($firstPackageTerm[$package['id']])) {
                                $firstPackageTerm[$package['id']] = $pricing['termId']; ?>
                            <?php } ?>
                            <tr>
                                <td class="text-center">
                                    <input class="priceTerm_<?php echo $package['id'];?>" name="priceTerm_<?php echo $package['id'];?>" type="radio" value="<?php echo $pricing['termId']; ?>" data-subtotal_amount="<?php echo $pricing['subtotal_amount']; ?>" <?php if($pricing['selected'] == 1) { echo " checked";} ?> onChange="loadTotalsInfo();" />
                                </td>
                                <td class="text-center"><?php echo $pricing['term'];?></td>
                                <td class="text-center"><?php echo $pricing['price'];?></td>
                                <?php if (!$this->hideSetupFees) { ?>
                                    <td class="text-right"><?php echo $pricing['setup'];?></td>
                                <?php } ?>
                                <td class="text-right" <?php if (!$this->showSaved) {?>style="display:none"<?php } ?>><?php if($this->showSaved) { echo $pricing['save'];}?></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>

                <?php if (isset($this->packageAddons[$package["id"]]) && is_array($this->packageAddons[$package["id"]]) && count($this->packageAddons[$package["id"]]) > 0) { ?>
                    <?php $addonStyle = ''; ?>
                    <?php foreach ($this->packageAddons[$package["id"]] as $packageTerm => $addonOptions) { ?>
                        <div id="upgradeAddonDescription_<?php echo $package["id"]; ?>_<?php echo $packageTerm; ?>" class="form-group upgradeAddonDescription" <?php echo $addonStyle; ?> >
                            <?php if (count($addonOptions) > 0) { ?>
                            <div class="addons-wrapper container-fluid">
                                <h2><?php echo $this->user->lang("Product Add-ons");?></h2>

                                <?php foreach ($addonOptions as $addon) {
                                    if (!is_array($addon['prices']) || count($addon['prices']) == 0) {
                                        continue;
                                    }

                                    ?>
                                    <div class="col-xs-12 col-sm-5 form-group addon-type">
                                        <label class="customfield_label control-label">
                                            <?php if ($addon['desclanguage'] != '') { ?>
                                            <span data-toggle="popover-hover" data-html="true" data-placement="top" title="<?php echo $this->user->lang("Description");?>" data-content="<?php echo $this->escape($addon['desclanguage']);?>" class="tip-target">
                                            <?php } ?>
                                                <b><?php echo $this->user->lang($addon['namelanguage']);?></b>
                                            <?php if ($addon['desclanguage'] != '') { ?>
                                            </span>
                                            <?php } ?>
                                        </label>


                                        <?php switch (@$addon['addon_type']) {
                                            case '2':    // quantity ?>
                                                <?php $countAddonOptions = count($addon['prices']); ?>
                                                <table style="width:100%">
                                                    <tr>
                                                        <td style="width:75px">
                                                            <?php echo $this->user->lang("Quantity");?> *</br>
                                                        </td>
                                                        <td>
                                                            <?php if ($countAddonOptions > 1) { ?>
                                                                <?php echo $this->user->lang("Option");?></br>
                                                            <?php } ?>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td style="width:75px">
                                                            <input type="number" min="0" style="width:70px;" id="addonQuantity_<?php echo $package["id"]; ?>_<?php echo $packageTerm; ?>_<?php echo $addon['id']; ?>" name="addonQuantity_<?php echo $package["id"]; ?>_<?php echo $packageTerm; ?>_<?php echo $addon['id']; ?>" class="quantity form-control" value="0" onChange="loadTotalsInfo();">
                                                        </td>
                                                        <td>
                                                            <?php if ($countAddonOptions == 1) { ?>
                                                                <input type="hidden" name="addonSelect_<?php echo $package["id"]; ?>_<?php echo $packageTerm; ?>_<?php echo $addon['id']; ?>" value="addon_<?php echo $addon['id']; ?>_<?php echo $addon['prices'][0]['price_id']; ?>_<?php echo $addon['prices'][0]['recurringprice_cyle']; ?>" data-subtotal_amount="<?php echo $addon['prices'][0]['item_subtotal_amount']; ?>">
                                                                <?php
                                                                    //Removing Addon Name from the Addon Option Name if it is there at the beginning
                                                                    $prefix = $addon['namelanguage'];
                                                                    $str = $addon['prices'][0]['pricelanguage'];
                                                                    if (substr($str, 0, strlen($prefix)) == $prefix) {
                                                                        $str = substr($str, strlen($prefix));
                                                                    }
                                                                    echo $str;
                                                                ?>
                                                            <?php } else { ?>
                                                                <select name="addonSelect_<?php echo $package["id"]; ?>_<?php echo $packageTerm; ?>_<?php echo $addon['id']; ?>" class="selectpicker form-control" onChange="loadTotalsInfo();">
                                                                    <?php foreach ($addon['prices'] as $price) { ?>
                                                                    <option value="addon_<?php echo $addon['id']; ?>_<?php echo $price['price_id']; ?>_<?php echo $price['recurringprice_cyle']; ?>" data-subtotal_amount="<?php echo $price['item_subtotal_amount']; ?>" <?php echo $price['price_selected']; ?>><?php echo $price['pricelanguage']; ?></option>
                                                                    <?php } ?>
                                                                </select>
                                                            <?php } ?>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="2">
                                                            <?php echo "* ".$this->user->lang("Prices will be multiplied by the quantity");?></br>
                                                        </td>
                                                    </tr>
                                                </table>
                                                <?php break;
                                            case '0':    // dropdown ?>
                                                <select name="addonSelect_<?php echo $package["id"]; ?>_<?php echo $packageTerm; ?>_<?php echo $addon['id']; ?>" class="selectpicker form-control" onChange="loadTotalsInfo();">
                                                    <?php foreach ($addon['prices'] as $price) { ?>
                                                    <option value="addon_<?php echo $addon['id']; ?>_<?php echo $price['price_id']; ?>_<?php echo $price['recurringprice_cyle']; ?>" data-subtotal_amount="<?php echo $price['item_subtotal_amount']; ?>" <?php echo $price['price_selected']; ?>><?php echo $price['pricelanguage']; ?></option>
                                                    <?php } ?>
                                                </select>
                                                </br>
                                                <?php break;
                                            case '1':    // radio buttons
                                                foreach ($addon['prices'] as $price) { ?>
                                                    <div>
                                                        <label class="radio">
                                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="addonSelect_<?php echo $package["id"]; ?>_<?php echo $packageTerm; ?>_<?php echo $addon['id']; ?>" class="dropdown" id="addonSelect_<?php echo $package["id"]; ?>_<?php echo $packageTerm; ?>_<?php echo $addon['id']; ?>" value="addon_<?php echo $addon['id']; ?>_<?php echo $price['price_id']; ?>_<?php echo $price['recurringprice_cyle']; ?>" data-subtotal_amount="<?php echo $price['item_subtotal_amount']; ?>" style="background:none; border:0px;" <?php echo $price['price_selected']; ?> onChange="loadTotalsInfo();">
                                                            <?php echo $price['pricelanguage']; ?>
                                                        </label>
                                                    </div>
                                                <?php }
                                                break;
                                        } ?>
                                        </br>
                                    </div>
                                <?php } ?>
                            </div>
                            <?php } ?>
                        </div>
                        <?php if ($firstPackageTerm[$package['id']] !== $packageTerm) {
                            $addonStyle = 'style="display:none"';
                        } ?>
                    <?php } ?>
                <?php } ?>

                <?php if ($firstPackageId === false) {
                    $firstPackageId = $package["id"];
                    $packageStyle = 'style="display:none"';
                } ?>
            </div>
        <?php } ?>

        <div align="right">
            <table cellpadding="4" cellspacing="4" border=0 width="100%">
                 <tr>
                    <td align='right' class='totallabel'>
                        <?php echo $this->user->lang("SubTotal"); ?>:
                    </td>
                    <td width='100px' class='totallabel' align='right'>
                        <strong class='total_subtotal_price'>
                        </strong>
                    </td>
                </tr>
                <tr class='total_coupon_discount_row' <?php echo ($this->upgradeDowngradeStatus['upgradeValue'] == 0) ? 'style="display:none;"' : ''; ?> >
                    <td align='right' class='totallabel'>
                        <?php echo $this->user->lang("Prorated Credit"); ?>:
                    </td>
                    <td class='totallabel' width='100px' style='text-align:right;'>
                        <strong class='total_subtotal_couponDiscount'>
                        </strong>
                    </td>
                </tr>
                <tr class='total_tax_row'>
                    <td align='right' class='totallabel'>
                        <?php echo $this->user->lang($this->customerTaxName) . ' (' . (float)$this->customerTax . '%)'; ?>:
                    </td>
                    <td class='totallabel' width='100px' style='text-align:right;'>
                        <strong class='total_tax_amount'>
                        </strong>
                    </td>
                </tr>
                <tr class='total_tax2_row'>
                    <td align='right' class='totallabel'>
                        <?php echo $this->user->lang($this->customerTax2Name) . ' (' . (float)$this->customerTax2 . '%)'; ?>:
                    </td>
                    <td class='totallabel' width='100px' style='text-align:right;'>
                        <strong class='total_tax2_amount'>
                        </strong>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="height:15px;">
                    </td>
                </tr>
                <tr bgcolor='#eeeeee'>
                    <td class='totallabel' align='right' style='height:30px;'>
                        <strong>
                            <?php echo $this->user->lang("Grand Total");?>:
                        </strong>
                    </td>
                    <td width='120px' class='totallabel' style='text-align:right;font-size:larger;height:7px;'>
                        <strong class='total_total_pay'>
                        </strong>
                    </td>
                </tr>
            </table>
        </div>
        <br />
        <div class="pull-right">
            <div class="form-group">
                <input id="cancel-button" type="button" value="<?php echo $this->user->lang('Cancel'); ?>" class="btn" />
                <input id="submit-button" type="submit" value="<?php echo $this->user->lang('Submit'); ?>" class="btn btn-success" />
            </div>
        </div>
    </form>
</div>