    <?php echo $this->partial('signuppublic/cartheader.phtml', array('tempInformation'=>$this->tempInformation,'user'=>$this->user,'step'=>$this->step, 'summary'=>$this->summary));?>
<?php
    $numpaymentmethods = count($this->paymentmethods);
    $customFields = json_encode($this->customFields);
?>
<script data-cfasync="false" type="text/javascript">
    $(document).ready(function(){
        cart = cart || {};
        <?php echo "var customFields = ". $customFields . ";\n"; ?>
        cart.process_profile_customfields(customFields);
        //cart.get_package_customfields(customFields);
    });
</script>


<div class="ce-box col-xs-12">
    <div class="ce-box-inner col-xs-12">

        <a href="order.php" class="pull-right btn btn-lg btn-danger btn-continue"><?php echo $this->user->lang("Continue Shopping");?></a>

        <form action="order.php?step=3" method="post">
        <h1><?php echo $this->user->lang("Order Summary");?></h1>
        <p class="sub_header">
        <?php echo $this->user->lang("Please review your order and make any necessary adjustments before proceeding to checkout.");?>
        </p>

        <table class="table table-striped table-responsive">
            <thead>
              <tr>
                <th></th>
                <th></th>
                <th width="150" style="text-align: right;padding-right:18px;"><span class="cart-item-title"><?php echo $this->user->lang('Price');?></span></th>
              </tr>
            </thead>
            <?php if (is_array($this->cartItems)) { ?>
            <tbody>
                <?php $proRateDate = ''; ?>
                <?php foreach ($this->cartItems as $item) { ?>
                    <tr>
                        <td>
                            <?php if ($item['groupType'] == 3) { ?>
                                <span class="cart-item-title"><?php echo $this->escape($item['domainName']) ?> x <?php echo $item['term']; ?> <?php if (@$item['titleText']) {
                                    echo "(".$item['titleText'].")";
}?></span>
                            <?php } else { ?>
                                <span class="cart-item-title"><?php echo $item['groupNameLanguage']." / ".$item['namelanguage']; ?> <?php if (@$item['titleText']) {
                                    echo $item['titleText'];
}?></span>
                            <?php } ?>
                            <?php if ($item['associatedDomain'] != false) {
?><br /> <?php echo $this->escape($item['associatedDomain']) ?> <?php
} ?>

                            <?php if ($item['hasAddons']) {?>
                                <a style="cursor: pointer;" onclick="cart.toggle_addons('<?php echo $item['cartItemId'];?>');"><br /><span id="toggle_addon_icon_<?php echo $item['cartItemId'];?>" style="width:15px;display:block;float:left;margin-top:1px;"><i class="fa fa-plus"></i></span> <span id="toggle_addon_text_<?php echo $item['cartItemId'];?>" class=""><?php echo $this->user->lang('Show Product Addons');?></span></a>
                                <div id="addons-<?php echo $item['cartItemId'];?>" style="clear: both; display:none; font-size:smaller;">
                                    <?php $showQuantityNote = false;
                                    foreach ($item['addons'] as $addon) {
                                        $quantityText = '';
                                        if ($addon['isQuantity']) {
                                            $quantityText = '. <b>'.$this->user->lang('Quantity').': '.$addon['addonQuantity'].'**</b>';
                                            $showQuantityNote = true;
                                        } ?>
                                        <i class="fa fa-ok addon-ok"></i> <?php echo $addon['namelanguage']; ?> - <?php echo $addon['itemlanguage']; ?><?php echo $quantityText; ?><br/>
                                    <?php }
                                    if ($showQuantityNote) {
                                        echo '<b><i>** '.$this->user->lang('Prices are per unit purchased.').'</i></b>';
                                    } ?>
                                </div>
                            <?php } ?>
                        </td>
                        <td valign="top" align="left"> <?php if (!isset($item['hidden']['delete'])) {
?><a onclick="cart.confirmCartDelete(
                '<?php echo $item['safeGroupName'];?> / <?php echo $item['safeName'];?>',
                '<?php echo $item['cartItemId'];?>',
                <?php if (isset($item['isBundle']) && is_array($item['isBundle']) && count($item['isBundle']) > 0) {
                        echo true;
                    } else {
                        echo false;
                    }?>
            );" style="color:#900; cursor: pointer;"><?php echo $this->user->lang('Remove');?></a> <?php
} ?><?php if (@$this->acceptCoupons) {
?><?php if (!isset($item['hidden']['delete'])) {
?>|<?php
}?> <a onclick="cart.applyCoupon('<?php echo $item['cartItemId'];?>', '<?php echo $item['appliedCoupon'];?>');" style="cursor: pointer;"><?php if (@$item['hasCoupon']) {
    echo $this->user->lang('Update Coupon');
} else {
    echo $this->user->lang('Apply Coupon');
}?></a><?php
} ?></td>
                        <td valign="top" style="text-align: right;padding-right:18px">
                            <?php if (@$item['newTotal'] && $item['newTotal'] != $item['totalFormatted']) {
                                    echo '<span style="text-decoration: line-through;color:#999;"> '.$item['totalFormatted'] .'</span> <span style="color:red;">'.$item['newTotal'].'</span>';
} else {
    echo $item['totalFormatted'];
}?><?php
if (isset($item['isProRated']) && $item['isProRated']) {
    echo "*";
    $proRateDate = $item['proRateDate'];
} ?><?php
if (@$item['newSetup']) {
  //lets only show a line through the one time fee if the coupon applied and prices are different
    if ($item['setupFormatted'] != $item['newSetup']) {
        echo '<br/><span style="text-decoration: line-through;"> '.$item['setupFormatted'] .' '.$this->user->lang('Setup Fee').'</span> <br/> <span style="color:red;">'.$item['newSetup'].' '.$this->user->lang('Setup Fee').'</span>';
    } else {
        echo '<br/>'.$this->user->lang('Setup Fee')." ".$item['newSetup'];
    }
} elseif (@$item['setupFormatted']) {
    echo "<br/> ".$this->user->lang('Setup Fee')." ".$item['setupFormatted'];
} ?>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        <?php } else {
                //should be redirected to order=0
}
        ?>
        </table>
        </form>

        <div class="total-box">
            <div class="get_total_image">
                <i class="fa fa-spinner fa fa-spin fa fa-large"></i>&nbsp;&nbsp;<?php echo $this->user->lang("Calculating Totals ...");?>
            </div>
            <div id="taxInformation">

                <div align="right">
                    <table cellpadding="4" cellspacing="4" border=0 width="100%">
                    <?php
                        echo "<tr><td align='right' class='totallabel'>".$this->user->lang("SubTotal")." (<span class='total_item_count'></span>):</td><td width='100px' class='totallabel' align='right'><strong class='total_subtotal_price'></strong></td></tr>";
                        echo "<tr class='total_coupon_discount_row'><td align='right' class='totallabel'>".$this->user->lang("Discounts").":</td><td class='totallabel' width='100px' style='text-align:right;'><strong class='total_subtotal_couponDiscount'></strong></td></tr>";
                        echo "<tr class='total_tax_row'><td align='right' class='totallabel'><span class='total_tax_name'></span>:</td><td class='totallabel' width='100px' style='text-align:right;'><strong class='total_tax_amount'></strong></td></tr>";
                        echo "<tr class='total_tax2_row'><td align='right' class='totallabel'><span class='total_tax2_name'></span>:</td><td class='totallabel' width='100px' style='text-align:right;'><strong class='total_tax2_amount'></strong></td></tr>";
                    ?>
                        <tr><td colspan="2" style="height:15px;"></td></tr>
                        <tr bgcolor='#eeeeee'><td class='totallabel' align='right' style='height:30px;'><strong><?php echo $this->user->lang("Grand Total");?>:</strong></td><td width='120px' class='totallabel' style='text-align:right;font-size:larger;height:7px;'><strong class='total_total_pay'></strong></td></tr>
                    <?php
                    if ($proRateDate != '') {
                        echo "<tr><td align='left' class='totallabel' colspan='2'>* ".$this->user->lang("Prorated to")." ".$proRateDate."</td></tr>";
                    }
                    ?>
                    </table>
                </div>

            </div>
        </div>

        <br/>

        <div id="loggedInBox" class="alert ce-alert ce-alert-success" style=" <?php if (!$this->loggedIn) {
?>visibility:hidden; display:none;<?php
} ?>">
            <strong><?php echo $this->user->lang("Logged in as");?> <span id="user-firstName"><?php echo @$this->gUserFirstName; ?></span> <span id="user-lastName"><?php echo @$this->gUserLastName; ?> (<?php echo $this->gCustomerEmail;?>)</span></strong>
            <br/>
            <?php echo $this->user->lang("If you wish to add this order under a new account please log out before completing this transaction.");?>
        </div>


        <?php if (@$this->fieldError) { ?>
            <div style='border:1px solid #cdcdcd; background:#ffeded; color:#900; margin-bottom:20px; padding:10px;-moz-border-radius: 5px;-webkit-border-radius: 5px;'><?php echo $this->fieldError;?></div>
        <?php } ?>

        <?php if (!$this->loggedIn) { ?>

            <div class="register-block col-xs-12">
                <div class="cart-register col-xs-12 col-sm-4">
                    <h2 class="dont_have_account_header"><?php echo $this->user->lang("Don't have an account yet?");?></h2>
                    <button class="ce-btn btn-danger btn-wide" type="button" onclick="cart.toggle_users('new',<?php echo $numpaymentmethods;?>);" ><?php echo $this->user->lang("Register");?></button>
                </div>

                <div class="add-options-or col-xs-12 col-sm-3">
                    <div><?php echo $this->user->lang('or') ?></div>
                </div>

                <div class="cart-dialog demo-dialog col-xs-12 col-sm-5">
                  <h2 class="have_account_header"><?php echo $this->user->lang("Already have an account? Log in");?></h2>
                  <form class="control-group" method="post" action="index.php?fuse=admin&action=Login">
                    <div class="form-group">
                        <input type="text" name="email" placeholder="<?php echo $this->user->lang('Login Email') ?>" class="flat form-control">
                    </div>
                    <div class="form-group">
                        <input type="password" name="passed_password" placeholder="<?php echo $this->user->lang('Password') ?>" class="flat form-control">
                        <input type="hidden" name="redirct_url" value="order.php?step=3" />
                    </div>
                    <div class="form-group">
                        <button class="ce-btn btn btn-primary form-control btn-inverse btn-wide btn-cart-user-login" type="submit"><?php echo $this->user->lang("Login");?></button>
                    </div>
                  </form>
                </div>
                <div style="clear:both;"></div>
            </div>

        <?php } ?>

    </div>
</div>

<form name="customerdata" class="customerdata" action="order.php?fuse=admin&controller=signup&action=process" method="POST" id="submitForm">

<div class="ce-box col-xs-12 customerdata" style="display:none;">
    <div class="ce-box-inner col-xs-12">
        <button class="pull-right ce-btn btn-info btn-wide btn-already-registered" type="button" onclick="cart.toggle_users('existing',<?php echo $numpaymentmethods;?>);" ><?php echo $this->user->lang("Already Registered?");?></button>
        <p class="alert ce-alert ce-alert-info"><?php echo $this->user->lang("Please enter your new profile and billing details below to continue.");?>
        </p>

        <div class="customfields-wrapper form-group"></div>

        <?php if ($this->showCaptcha) { ?>
        <div class="customfield customfield_not_ingroup recaptcha col-xs-12">
            <label class="customfield_label">
                <div class="g-recaptcha" data-sitekey="<?php echo $this->captchaPublicKey; ?>"></div>
                <script type="text/javascript" src="https://www.google.com/recaptcha/api.js"></script>
            </label>
        </div>
        <?php } ?>
    </div>
</div>

<div class="ce-box col-xs-12 customerdata" id="paymentInformation" style="display:none;">
    <div class="ce-box-inner col-xs-12">

        <div class="payment_information_box">
            <input id="payment_information_display" type="hidden" name="payment_information_display" value="0">
            <input id="hidePaymentMethods" type="hidden" name="hidePaymentMethods" value="<?php echo $this->hidePaymentMethods; ?>">
            <input id="totalPay_raw" type="hidden" name="totalPay_raw" value="0">
            <input id="creditBalance_raw" type="hidden" name="creditBalance_raw" value="<?php echo $this->creditbalance; ?>">
            <?php if (count($this->paymentmethods) != 0) { ?>
                <h1 class="make_payment_using"><?php echo $this->user->lang("Choose Your Payment Method");?></h1>

                <label class="checkbox credit_balance_option" style="display:none;">
                    <input class="credit_balance_checkbox" type="checkbox" name="applymycredit" checked="checked" disabled /><?php echo $this->user->lang("Apply my credit of").' '.$this->formattedcreditbalance.' '.$this->user->lang("and pay the rest with:");?>
                </label>

                <span class="credit_balance_payment_option" style="display:none;">
                    <label class="radio payment_method_radio_label payment_method_selected">
                        <input type="radio" class="payment_method_apply_my_credit" onclick="cart.toggle_gateway(this.value);" name="paymentMethod" checked="checked" value="apply_my_credit" /> <span class="make_payment_option"><?php echo $this->user->lang("Apply my Credit").' ['.$this->user->lang("Available").': '.$this->formattedcreditbalance.']';?>&nbsp;&nbsp;&nbsp;</span>
                    </label>
                </span>

                <?php foreach ($this->paymentmethods as $tmpKey => $key) { ?>
                    <?php if ($key['paymentTypeOptionValue'] == "paypal") {
                        $key['description'] = $this->user->lang("Click the button below to log into PayPal and make your payment.");
} elseif ($key['iscreditcard']) {
    $key['description'] = $this->user->lang("Make a secure payment using your credit card.");
} ?>

                    <label class="radio payment_method_radio_label <?php if ($key['paymentTypeOptionSelected']) {
                        echo "payment_method_selected";
} ?>">
                        <div class="pull-right billing_accepting_cc">
                            <?php foreach ($key['weaccept']['options'] as $weAccept) { ?>
                                <img src="<?php echo $weAccept['img'];?>" id="<?php echo $weAccept['id'];?>" alt="<?php echo $weAccept['alt'];?>">
                            <?php } ?>
                        </div>
                        <input type="radio" class="paymentMethod payment_method_<?php echo $key['paymentTypeOptionValue'];?>" name="paymentMethod" <?php if ($key['paymentTypeOptionSelected']) {
?> checked="checked" <?php
} ?> value="<?php echo $key['paymentTypeOptionValue'];?>" /> <span class="make_payment_option"><?php echo ($key['paymentTypeOptionValue'] == "apply_my_credit")? $key['paymentTypeOptionLabel'].'['.$this->user->lang("Available").': '.$this->formattedcreditbalance.']' : $this->user->lang("Pay with")." ".$key['paymentTypeOptionLabel'];?></span>
                        <div id="payment_desc"><?php echo $key['description'];?></div>
                    </label>
                <?php } ?>
            <?php } else { ?>
                <strong><?php echo $this->user->lang('There are no Payment Processors configured!');?></strong>
            <?php } ?>

            <!-- Handle the extra fields for payment processors -->
            <?php foreach ($this->paymentmethods as $key) { ?>

                <input type="hidden" name="<?php echo $key['paymentTypeOptionValue']."_autopayment"?>" id="<?php echo $key['paymentTypeOptionValue']."_autopayment"?>" value="<?php echo $key['autoPayment'];?>"></input>
                <?php if (@is_array($key['extraFields'])) { ?>
                    <div class="payment_method_extra_fields<?php echo (!$key['paymentTypeOptionSelected']) ? ' hidden' : ''; ?>" id="<?php echo $key['paymentTypeOptionValue'];?>-extraFields">
                    <?php foreach ($key['extraFields'] as $field) { ?>
                        <?php $popupstr  = ""; ?>
                        <?php $requiredtype = ""; ?>
                    <?php if ($field['fieldType'] == "hidden") { ?>
                        <input name="<?php echo $field['fieldName'];?>" type="hidden" value="<?php echo @$field['fieldValue'];?>" />
                        <?php continue; ?>
                    <?php } ?>
                    <?php if (isset($field['fieldDescription']) && $field['fieldDescription'] != "") { ?>
                        <?php $popupstr = 'data-toggle="popover-hover" data-html="true" data-placement="top" title="Description" data-content="'.addslashes($field['fieldDescription']).'" class="tip-target"'; ?>
                    <?php } ?>
                    <?php if ($field['labelpos'] != "low" && $field['fieldType'] != 'grouplabel') { ?>
                        <div class="col-xs-12">
                            <label for="<?php echo $field['fieldName'];?>">
                                <span <?php echo $popupstr; ?>><?php echo $field['fieldTitle'];?></span>
                            </label>
                        </div>
                    <?php } ?>
                    <div class="col-xs-12 <?php if (stripos($field['fieldName'], 'cvv') !== false) { ?>
                        col-xs-2
                        <?php } elseif ($field['fieldType'] != 'grouplabel') { ?>
                        col-xs-4
                        <?php } ?>">
                    <?php if ($field['fieldType'] == 'text') { ?>
                        <input id="<?php echo $field['fieldName'];?>" name="<?php echo $field['fieldName'];?>" <?php echo $requiredtype;?> type="text" value="<?php echo @$field['fieldValue'];?>"<?php echo (@$field['fieldDisabled']) ? ' disabled' : ''; ?> class="form-control">
                    <?php } elseif ($field['fieldType'] == 'dropdown' || $field['fieldType'] == 'yesno') { ?>
                        <select name="<?php echo $field['fieldName'];?>" <?php echo (@$field['fieldDisabled']) ? ' disabled' : ''; ?> class="selectpicker form-control">
                        <?php if ($field['fieldType'] == 'dropdown') { ?>
                            <?php foreach ($field['fieldValue'] as $value) { ?>
                                <option value="<?php echo $value['value'];?>" ><?php echo $value['text'];?></option>
                            <?php } ?>
                        <?php } elseif ($field['fieldType'] == 'yesno') { ?>
                            <option value="1"<?php echo ($field['fieldValue'] == 1) ? ' selected="selected"' : ''; ?>><?php echo $this->user->lang('Yes');?></option>
                            <option value="0"<?php echo ($field['fieldValue'] == 0) ? ' selected="selected"' : ''; ?>><?php echo $this->user->lang('No');?></option>
                        <?php } ?>
                        </select>
                    <?php } elseif ($field['fieldType'] == 'grouplabel') { ?>
                        <hr>
                        <label>
                            <strong><?php echo $field['fieldTitle']; ?></strong>
                        </label>
                    <?php } ?>
                    </div>
                    <?php if ($field['labelpos'] == "low" && $field['fieldType'] != 'grouplabel') { ?>
                        <div class="col-xs-12">
                            <label for="<?php echo $field['fieldName'];?>" class="sub_label">
                                <span <?php echo $popupstr; ?>><?php echo $field['fieldTitle'];?></span>
                            </label>
                        </div>
                    <?php } ?>
                    <?php } ?>
                    </div>
                <?php } ?>
            <?php } ?>


        <?php if (@$this->automaticCCCharge) { ?>
            <div class="cart_agree col-xs-12 form-group" id="autochargeccblock">
                <label class="checkbox">
                <input type="checkbox" name="autochargecc" id="autochargecc" checked>
                <?php echo $this->user->lang('I authorize that future charges for these packages will be automatically charged.'); ?>
                </label>
            </div>
        <?php } ?>
        </div>

        <?php if (@$this->termsConditions) { ?>

            <div class="cart_agree col-xs-12 col-sm-5 form-group center-on-mobile">
                <label class="checkbox">
                <input type="checkbox" onclick="cart.agree_tc();" name="agree" value="1">
                <?php echo $this->user->lang('I Agree to the'); ?>
                <?php if ($this->termsConditions == '-1') { ?>
                    <a href="<?php echo @$this->termsConditionsUrl;?>" target="_blank"><?php echo $this->user->lang('Terms and Conditions');?></a>
                <?php } else { ?>
                    <a onclick="cart.show_tc();" href="javascript:void(0);"><?php echo $this->user->lang('Terms and Conditions');?></a>
                    <div id="toc" class="hide"><?php echo $this->unescape($this->termsConditionsText) ?></div>
                <?php } ?>
                </label>
            </div>

        <?php } ?>

        <?php if (count($this->paymentmethods) != 0) { ?>

        <div class="form-actions col-xs-12 col-sm-6 form-group center-on-mobile">
            <span class='paymentbutton1'><a style="margin-left:0px;cursor:pointer;" class="btn-success btn btn-lg <?php if (@$this->termsConditions) {
?>disabled<?php
} ?>" onclick="cart.submit_form(<?php echo $this->loggedIn; ?>);"  id="submitButton"></a></span>
        <?php foreach ($this->gatewayForms as $gatewayName => $gatewayForm) { ?>
            <span class='paymentbutton2 <?php echo $gatewayName."paymentbutton"; ?> pull-right'>
                <?php echo $this->unescape($gatewayForm); ?>
            </span>
        <?php } ?>
        </div>

        <?php } ?>
    </div>
</div>

</form>

<script data-cfasync="false" type="text/javascript">
    var mainForm,paymentDescs = [];
    $(document).ready(function() {
        <?php if ($this->user->isAnonymous()) { ?>
        cart.main_button_text = "<?php echo $this->user->lang('Place Order and Create Account');?>";
        <?php } else { ?>
        cart.main_button_text = "<?php echo $this->user->lang('Place Order');?>";
        <?php } ?>
        mainForm = document.forms['customerdata'];
        cart.selected_gateway = '<?php echo @$this->defaultGateway;?>';
        cart.state_var_id = 'CT_<?php echo $this->state_var_id;?>';
        $("#"+cart.state_var_id).bind('blur',function(){
            validate_vat();//tax purposes
        });
        cart.country_var_id = 'CT_<?php echo $this->country_var_id;?>';
        $("#"+cart.country_var_id).bind('change',function(){
            validate_vat();//tax purposes
        });
        cart.vat_var_id = 'CT_<?php echo $this->vat_var_id;?>';
        $("#"+cart.vat_var_id).bind('blur',function(){
            validate_vat();//tax purposes
        });

        validate_vat();
        <?php if (!$this->loggedIn) { ?>
            cart.toggle_users('new',<?php echo $numpaymentmethods;?>);
        <?php } else { ?>
            $('#paymentInformation').show();
        <?php } ?>

        <?php foreach ($this->paymentmethods as $key) { ?>
        paymentDescs['<?php echo $key['paymentTypeOptionValue']; ?>'] = '<?php echo $key['description']; ?>';
        <?php } ?>
        <?php if (count($this->paymentmethods) == 1 && @$this->defaultGateway == '') { ?>
        cart.toggle_gateway('<?php echo $this->paymentmethods[0]['paymentTypeOptionValue']; ?>');
        <?php } else { ?>
        cart.toggle_gateway(cart.selected_gateway);
        <?php } ?>

    });
</script>

<?php if ($this->enableFraudLabsPro) { ?>
<script data-cfasync="false" type="text/javascript">
    (function(){
        function s() {
            var e = document.createElement('script');
            e.type = 'text/javascript';
            e.async = true;
            e.src = ('https:' === document.location.protocol ? 'https://' : 'http://') + 'cdn.fraudlabspro.com/s.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(e, s);
        }
        (window.attachEvent) ? window.attachEvent('onload', s) : window.addEventListener('load', s, false);
    })();
</script>
<?php } ?>

<?php if ($this->maxmind_device_tracking_enabled === true) { ?>
<script data-cfasync="false">
    maxmind_user_id = '<?php echo $this->maxmind_account_id; ?>';
    (function() {
        var loadDeviceJs = function() {
            var element = document.createElement('script');
            element.src = ('https:' == document.location.protocol ? 'https:' : 'http:') + '//device.maxmind.com/js/device.js';
            document.body.appendChild(element);
        };
        if (window.addEventListener) {
            window.addEventListener('load', loadDeviceJs, false);
        } else if (window.attachEvent) {
            window.attachEvent('onload', loadDeviceJs);
        }
    })();
</script>
<?php } ?>