<div id="signup-steps">
    <div class="secure-connection"><i class="fa fa-lock"></i>&nbsp;&nbsp;<?php echo $this->user->lang("Secure Connection");?></div>
    <div id="step-1" class="<?php echo ($this->step == 1 || $this->step==0) ? "on" : "off";?>"><?php echo $this->user->lang("1. Select Package");?></div>
    <div id="step-2" class="<?php echo ($this->step == 2) ? "on" : "off";?>"><?php echo $this->user->lang("2. Package Configuration");?></div>
    <div id="step-3" class="<?php echo ($this->step == 3 || $this->step == 4) ? "last-on" : "last-off";?>"><?php echo $this->user->lang("3. Payment Details");?></div>


    <div class="shopping_cart pull-right">
        <a href="order.php?step=3">
            <div class="cart-summary-btn img-circle">
                <i class="fa fa-shopping-cart fa-light"></i>
            </div>
            <span class="badge badge-important cart-badge"><?php echo $this->summary['cartCount'];?></span>
        </a>
    </div>
</div>