<?php if (!in_array(trim($this->group['descriptionlanguage']), array("", "<p><br></p>"))) { ?>
    <div class="alert ce-alert ce-alert-info">
        <?php echo $this->group['descriptionlanguage'];?>
    </div>
<?php } ?>

<h1><?php echo $this->user->lang("Select a Package");?></h1>
<div class="panel-group selectedproduct-configuration-accordion" id="product-accordion" style="display: block;">

<?php
    $count_defined_packages = 0;
    foreach ($this->packages as $package) {
        if (!is_array($package['pricing']) || count($package['pricing']) == 0) {
            continue;
        }
        $count_defined_packages++;
?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a class="accordion-group-options" <?php echo ($package['selected']) ? '' : ' class="collapsed"' ;?>" data-toggle="collapse" data-parent="#product-accordion" href="#collapse<?php echo $package['id'];?>">
                    <?php echo $package['plannamelanguage']; ?>
                    <?php if ($package['stockLevel'] >= 0) {
                        if ($package['stockControl'] == 1) {
                            echo '&nbsp;&nbsp;[ '.$this->user->lang("not available").' ]';
                        } else {
                            echo '&nbsp;&nbsp;[ '.$package['stockLevel'].' '.$this->user->lang("available").' ]';
                        }
                    } ?>
                </a>
            </h4>
        </div>
        <div id="collapse<?php echo $package['id'];?>" class="panel-collapse collapse<?php echo ($package['selected']) ? " in" : "" ;?>">
            <div class="panel-body">
               <?php echo $this->unescape($package['descriptionlanguage']);?>
                <div class="table-responsive">
                    <table class="table ce-table table-striped table-hover pricing-options table-responsive">
                        <thead>
                            <tr class="caption">
                                <th class="text-center" width="15"></th>
                                <th class="text-center" width="300"><?php echo $this->user->lang("Term Length");?></th>
                                <th><?php echo $this->user->lang("Price Per Term");?></th>
                                <?php if (!$this->hideSetupFees): ?>
                                    <th class="text-right"><?php echo $this->user->lang("Setup Fee");?></th>
                                <?php endif ?>
                                <th class="text-right" <?php if (!$this->showSaved) {?>style="display:none"<?php } ?>><?php if($this->showSaved) { echo $this->user->lang("You Save");}?></th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($package['pricing'] as $pricing) { ?>
                            <tr>
                                <td class="text-center">
                                    <input class="priceTerm_<?php echo $package['id'];?>" name="priceTerm_<?php echo $package['id'];?>" type="radio" value="<?php echo $pricing['termId'];?>" <?php if($package['stockControl'] == 0 && $pricing['selected'] == 1) { echo " checked";} elseif($package['stockControl'] == 1){ echo " disabled";}?> />
                                </td>
                                <td class="text-center"><?php echo $pricing['term'];?></td>
                                <td><?php echo $pricing['price'];?></td>
                                <?php if (!$this->hideSetupFees): ?>
                                    <td class="text-right"><?php echo $pricing['setup'];?></td>
                                <?php endif ?>
                                <td class="text-right" <?php if (!$this->showSaved) {?>style="display:none"<?php } ?>><?php if($this->showSaved) { echo $pricing['save'];}?></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>

                <div class="configuration-update-wrap">
                    <div class="form-actions">
                          <a type="submit" href="<?php echo $package['nextUrl'];?>" data-package-id="<?php echo $package['id'];?>" class="pull-right btn btn-primary btn-gotosetp2-submit"><?php echo $this->user->lang('Continue') ?></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php } ?>


    <?php if ($count_defined_packages == 0) { ?>
        <div class="alert ce-alert ce-alert-error">
            <?php echo $this->user->lang("There are no packages configured for this package type"); ?>
        </div>
    <?php } ?>


</div>

<?php if ( $this->bundled ) { ?>
<script data-cfasync="false" type="text/javascript">
    $(document).ready(function() {
        $('a:not(.button, .btn, .accordion-toggle, .accordion-group-options, .dropdown-toggle)').click(function(e){
            e.stopImmediatePropagation();
            var selectedLink = this;
            if ($(this).hasClass('showcancelalert')) {
                RichHTML.msgBox(lang('Are you sure you want to cancel this item?'),
                {
                    type: 'yesno'
                },
                function(result) {
                    if (result.btn == lang('Yes')) {
                        confirmDleteItemFromCart(selectedLink);
                    }
                });
                return false;
            } else if ($(this).hasClass('nopopupalert')) {
                confirmDeleteItemFromCart(selectedLink);
            } else {
                RichHTML.msgBox(lang('Leaving now will cancel this item.  Are you sure you want to leave?'),
                {
                    type: 'yesno'
                },
                function(result) {
                    if (result.btn == lang('Yes')) {
                        confirmDleteItemFromCart(selectedLink);
                    }
                });
                return false;
            }
        });
    });


    confirmDleteItemFromCart = function(link)
    {
        var cartItem = "<?php echo $this->cartParentPackage;?>";
        if(cartItem != ''){
            $.ajax({
            url: 'index.php?fuse=admin&controller=signup&action=deletecartitem',
                success: function () {
                    window.location = link;
            },
            data: { cartItem: cartItem },
            dataType: 'json'
        });
      } else {
        window.location = link;
      }
    }
</script>
<?php } ?>
